# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 11.1
# Mon Jul 25 11:09:58 MYT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_eth_timestamp_req_ctrl "altera_eth_timestamp_req_ctrl" v1.0
# | null 2011.07.25.11:09:58
# | 
# | 
# | /data/skyeow/p4root/acds/main/ip/ethernet/ethernet_ucore/altera_eth_timestamp_req_ctrl/altera_eth_timestamp_req_ctrl.v
# | 
# |    ./altera_eth_timestamp_req_ctrl.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.1
# | 
#package require -exact qsys 11.0
# | 
# +-----------------------------------
package require -exact sopc 9.1
# +-----------------------------------
# | module altera_eth_timestamp_req_ctrl
# | 
set_module_property DESCRIPTION "Altera Ethernet Timestamp Request Control"
set_module_property NAME altera_eth_timestamp_req_ctrl
set_module_property GROUP "Interface Protocols/Ethernet/Submodules"
set_module_property VERSION 13.1
set_module_property AUTHOR "Altera Corporation"
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME "Ethernet Timestamp Request Control"
set_module_property TOP_LEVEL_HDL_FILE altera_eth_timestamp_req_ctrl.v
set_module_property TOP_LEVEL_HDL_MODULE altera_eth_timestamp_req_ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL false
set_module_property STATIC_TOP_LEVEL_MODULE_NAME altera_eth_timestamp_req_ctrl
set_module_property FIX_110_VIP_PATH false
set_module_property ELABORATION_CALLBACK elaborate
# | 
# +-----------------------------------

# -----------------------------------
# IEEE encryption
# ----------------------------------- 
add_fileset simulation_verilog SIM_VERILOG sim_ver
add_fileset simulation_vhdl SIM_VHDL sim_vhd
set_fileset_property simulation_verilog TOP_LEVEL altera_eth_timestamp_req_ctrl

proc sim_ver {name} {
    if {1} {
        add_fileset_file mentor/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "mentor/altera_eth_timestamp_req_ctrl.v" {MENTOR_SPECIFIC}
    }
    if {1} {
        add_fileset_file aldec/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "aldec/altera_eth_timestamp_req_ctrl.v" {ALDEC_SPECIFIC}
    }
    if {0} {
        add_fileset_file cadence/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "cadence/altera_eth_timestamp_req_ctrl.v" {CADENCE_SPECIFIC}
    }
    if {0} {
        add_fileset_file synopsys/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_timestamp_req_ctrl.v" {SYNOPSYS_SPECIFIC}
    }
    add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
    add_fileset_file altera_avalon_st_clock_crosser.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_clock_crosser.v"
    add_fileset_file altera_avalon_st_pipeline_base.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_base.v"
    add_fileset_file altera_avalon_st_splitter.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_splitter/altera_avalon_st_splitter.sv"
}

proc sim_vhd {name} {
    if {1} {
        add_fileset_file mentor/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "mentor/altera_eth_timestamp_req_ctrl.v" {MENTOR_SPECIFIC}
	add_fileset_file mentor/altera_avalon_st_pipeline_base.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/mentor/altera_avalon_st_pipeline_base.v" {MENTOR_SPECIFIC}
    }
    if {1} {
        add_fileset_file aldec/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "aldec/altera_eth_timestamp_req_ctrl.v" {ALDEC_SPECIFIC}
	add_fileset_file aldec/altera_avalon_st_pipeline_base.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/aldec/altera_avalon_st_pipeline_base.v" {ALDEC__SPECIFIC}
    }
    if {0} {
        add_fileset_file cadence/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "cadence/altera_eth_timestamp_req_ctrl.v" {CADENCE_SPECIFIC}
	add_fileset_file cadence/altera_avalon_st_pipeline_base.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/cadence/altera_avalon_st_pipeline_base.v" {CADENCE_SPECIFIC}
    }
    if {0} {
        add_fileset_file synopsys/altera_eth_timestamp_req_ctrl.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_timestamp_req_ctrl.v" {SYNOPSYS_SPECIFIC}
	add_fileset_file synopsys/altera_avalon_st_pipeline_base.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/synopsys/altera_avalon_st_pipeline_base.v" {SYNOPSYS_SPECIFIC}   
    }
    add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
    add_fileset_file altera_avalon_st_clock_crosser.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_clock_crosser.v"
    add_fileset_file altera_avalon_st_splitter.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_splitter/altera_avalon_st_splitter.sv"
}


# +-----------------------------------
# | files
# | 
add_file altera_eth_timestamp_req_ctrl.v {SYNTHESIS}
add_file altera_eth_timestamp_req_ctrl.ocp {SYNTHESIS}
add_file $env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v {SYNTHESIS}
add_file $env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_clock_crosser.v {SYNTHESIS}
add_file $env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_base.v {SYNTHESIS}
add_file $env(QUARTUS_ROOTDIR)/../ip/altera/avalon_st/altera_avalon_st_splitter/altera_avalon_st_splitter.sv {SYNTHESIS}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter BITSPERSYMBOL INTEGER 8
set_parameter_property BITSPERSYMBOL DEFAULT_VALUE 8
set_parameter_property BITSPERSYMBOL DISPLAY_NAME BITSPERSYMBOL
set_parameter_property BITSPERSYMBOL TYPE INTEGER
set_parameter_property BITSPERSYMBOL ENABLED false
set_parameter_property BITSPERSYMBOL UNITS None
set_parameter_property BITSPERSYMBOL AFFECTS_GENERATION false
set_parameter_property BITSPERSYMBOL HDL_PARAMETER true

add_parameter SYMBOLSPERBEAT INTEGER 8
set_parameter_property SYMBOLSPERBEAT DEFAULT_VALUE 8
set_parameter_property SYMBOLSPERBEAT DISPLAY_NAME SYMBOLSPERBEAT
set_parameter_property SYMBOLSPERBEAT TYPE INTEGER
set_parameter_property SYMBOLSPERBEAT ENABLED false
set_parameter_property SYMBOLSPERBEAT UNITS None
set_parameter_property SYMBOLSPERBEAT AFFECTS_GENERATION false
set_parameter_property SYMBOLSPERBEAT HDL_PARAMETER true

add_parameter ERROR_WIDTH INTEGER 1
set_parameter_property ERROR_WIDTH DEFAULT_VALUE 1
set_parameter_property ERROR_WIDTH DISPLAY_NAME ERROR_WIDTH
set_parameter_property ERROR_WIDTH TYPE INTEGER
set_parameter_property ERROR_WIDTH ENABLED false
set_parameter_property ERROR_WIDTH UNITS None
set_parameter_property ERROR_WIDTH AFFECTS_GENERATION false
set_parameter_property ERROR_WIDTH HDL_PARAMETER true

add_parameter EMPTY_WIDTH INTEGER 3
set_parameter_property EMPTY_WIDTH DEFAULT_VALUE 3
set_parameter_property EMPTY_WIDTH DISPLAY_NAME EMPTY_WIDTH
set_parameter_property EMPTY_WIDTH TYPE INTEGER
set_parameter_property EMPTY_WIDTH ENABLED false
set_parameter_property EMPTY_WIDTH UNITS None
set_parameter_property EMPTY_WIDTH AFFECTS_GENERATION false
set_parameter_property EMPTY_WIDTH HDL_PARAMETER true

add_parameter FINGERPRINT_WIDTH INTEGER 4
set_parameter_property FINGERPRINT_WIDTH DEFAULT_VALUE 4
set_parameter_property FINGERPRINT_WIDTH DISPLAY_NAME FINGERPRINT_WIDTH
set_parameter_property FINGERPRINT_WIDTH TYPE INTEGER
set_parameter_property FINGERPRINT_WIDTH ENABLED true
set_parameter_property FINGERPRINT_WIDTH UNITS None
set_parameter_property FINGERPRINT_WIDTH AFFECTS_GENERATION false
set_parameter_property FINGERPRINT_WIDTH HDL_PARAMETER true

add_parameter USE_TIMESTAMP_INSERTER INTEGER 1
set_parameter_property USE_TIMESTAMP_INSERTER DEFAULT_VALUE 1
set_parameter_property USE_TIMESTAMP_INSERTER DISPLAY_NAME USE_TIMESTAMP_INSERTER
set_parameter_property USE_TIMESTAMP_INSERTER TYPE INTEGER
set_parameter_property USE_TIMESTAMP_INSERTER DISPLAY_HINT "boolean"
set_parameter_property USE_TIMESTAMP_INSERTER ENABLED true
set_parameter_property USE_TIMESTAMP_INSERTER UNITS None
set_parameter_property USE_TIMESTAMP_INSERTER AFFECTS_GENERATION false
set_parameter_property USE_TIMESTAMP_INSERTER HDL_PARAMETER false

add_parameter ENABLE_1G10G_MAC INTEGER 0
set_parameter_property ENABLE_1G10G_MAC DISPLAY_NAME "1G/10G MAC"
set_parameter_property ENABLE_1G10G_MAC DISPLAY_HINT boolean
set_parameter_property ENABLE_1G10G_MAC DESCRIPTION "Enable 1G/10G MAC support"
set_parameter_property ENABLE_1G10G_MAC HDL_PARAMETER false

# | 
# +-----------------------------------

proc elaborate {} {
    set fingerprint_width [ get_parameter_value FINGERPRINT_WIDTH ]
    set use_timestamp_inserter [ get_parameter_value USE_TIMESTAMP_INSERTER ]
    set enable_1g10g_mac [ get_parameter_value ENABLE_1G10G_MAC ]
    
    set_port_property time_stamp_req_data_sink_data WIDTH $fingerprint_width
    
    set_port_property timestamp_fingerprint_96b_data_src_data_fp WIDTH [expr $fingerprint_width]
    set_port_property timestamp_fingerprint_64b_data_src_data_fp WIDTH [expr $fingerprint_width]
    
    if {$enable_1g10g_mac == 0} {
        set_interface_property clk_1g ENABLED false
        set_interface_property reset_1g ENABLED false
        
        set_port_property clk_1g TERMINATION true
        set_port_property reset_1g TERMINATION true
        
        set_port_property clk_1g TERMINATION_VALUE 0
        set_port_property reset_1g TERMINATION_VALUE 1
        
        set_interface_property speed_select ENABLED false
        set_port_property speed_select TERMINATION true
        set_port_property speed_select TERMINATION_VALUE 0
        
        set_interface_property tsu_96b_1g_data_sink ENABLED false
        set_interface_property tsu_64b_1g_data_sink ENABLED false
        
        set_port_property tsu_96b_1g_data_sink_valid TERMINATION true
        set_port_property tsu_96b_1g_data_sink_data TERMINATION true
        
        set_port_property tsu_96b_1g_data_sink_valid TERMINATION_VALUE 0
        set_port_property tsu_96b_1g_data_sink_data TERMINATION_VALUE 0
        
        set_port_property tsu_64b_1g_data_sink_valid TERMINATION true
        set_port_property tsu_64b_1g_data_sink_data TERMINATION true
        
        set_port_property tsu_64b_1g_data_sink_valid TERMINATION_VALUE 0
        set_port_property tsu_64b_1g_data_sink_data TERMINATION_VALUE 0
    } else {
        set_interface_property tsu_96b_1g_data_sink ENABLED true
        set_interface_property tsu_64b_1g_data_sink ENABLED true
    }
    
    if {$use_timestamp_inserter == 1} {
        set_interface_property req_ctrl_valid_10g ENABLED true
        set_interface_property time_stamp_data_10g ENABLED true
        set_interface_property ctrl_signal_10g ENABLED true
        set_interface_property octet_location_10g ENABLED true
        
        if {$enable_1g10g_mac == 0} {
            set_interface_property req_ctrl_valid_1g ENABLED false
            set_interface_property time_stamp_data_1g ENABLED false
            set_interface_property ctrl_signal_1g ENABLED false
            set_interface_property octet_location_1g ENABLED false
        }
    } else {
        set_interface_property egress_timestamp_insert_control ENABLED false
        
        set_port_property etstamp_ins_timestamp_insert TERMINATION true
        set_port_property etstamp_ins_timestamp_format TERMINATION true
        
        set_port_property etstamp_ins_residence_time_update TERMINATION true
        set_port_property etstamp_ins_ingress_timestamp_96b TERMINATION true
        set_port_property etstamp_ins_ingress_timestamp_64b TERMINATION true
        set_port_property etstamp_ins_residence_time_calc_format TERMINATION true
        
        set_port_property etstamp_ins_checksum_zero TERMINATION true
        set_port_property etstamp_ins_checksum_correct TERMINATION true
        
        set_port_property etstamp_ins_offset_timestamp TERMINATION true
        set_port_property etstamp_ins_offset_correction_field TERMINATION true
        set_port_property etstamp_ins_offset_checksum_field TERMINATION true
        set_port_property etstamp_ins_offset_checksum_correction TERMINATION true
        
        set_port_property etstamp_ins_timestamp_insert TERMINATION_VALUE 0
        set_port_property etstamp_ins_timestamp_format TERMINATION_VALUE 0
        
        set_port_property etstamp_ins_residence_time_update TERMINATION_VALUE 0
        set_port_property etstamp_ins_ingress_timestamp_96b TERMINATION_VALUE 0
        set_port_property etstamp_ins_ingress_timestamp_64b TERMINATION_VALUE 0
        set_port_property etstamp_ins_residence_time_calc_format TERMINATION_VALUE 0
        
        set_port_property etstamp_ins_checksum_zero TERMINATION_VALUE 0
        set_port_property etstamp_ins_checksum_correct TERMINATION_VALUE 0
        
        set_port_property etstamp_ins_offset_timestamp TERMINATION_VALUE 0
        set_port_property etstamp_ins_offset_correction_field TERMINATION_VALUE 0
        set_port_property etstamp_ins_offset_checksum_field TERMINATION_VALUE 0
        set_port_property etstamp_ins_offset_checksum_correction TERMINATION_VALUE 0
        
        set_interface_property req_ctrl_valid_10g ENABLED false
        set_interface_property time_stamp_data_10g ENABLED false
        set_interface_property ctrl_signal_10g ENABLED false
        set_interface_property octet_location_10g ENABLED false
        
        set_interface_property req_ctrl_valid_1g ENABLED false
        set_interface_property time_stamp_data_1g ENABLED false
        set_interface_property ctrl_signal_1g ENABLED false
        set_interface_property octet_location_1g ENABLED false
    }
    
    set_port_property data_sink_error VHDL_TYPE STD_LOGIC_VECTOR
    set_port_property mux_data_sink_channel VHDL_TYPE STD_LOGIC_VECTOR
}

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clk_10g clock end
set_interface_property clk_10g ENABLED true
add_interface_port clk_10g clk_10g clk Input 1

add_interface clk_1g clock end
set_interface_property clk_1g ENABLED true
add_interface_port clk_1g clk_1g clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset_10g reset end
set_interface_property reset_10g associatedClock clk_10g
set_interface_property reset_10g synchronousEdges DEASSERT

set_interface_property reset_10g ENABLED true

add_interface_port reset_10g reset_10g reset Input 1

add_interface reset_1g reset end
set_interface_property reset_1g associatedClock clk_1g
set_interface_property reset_1g synchronousEdges DEASSERT

set_interface_property reset_1g ENABLED true

add_interface_port reset_1g reset_1g reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point egress_timestamp_request
# | 
add_interface egress_timestamp_request conduit end
set_interface_assignment egress_timestamp_request "ui.blockdiagram.direction" Input
set_interface_property egress_timestamp_request ENABLED true

add_interface_port egress_timestamp_request time_stamp_req_data_sink_valid valid Input 1
add_interface_port egress_timestamp_request time_stamp_req_data_sink_data fingerprint Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clk_10g
set_interface_property avalon_streaming_sink associatedReset reset_10g
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0

set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink data_sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink data_sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink data_sink_valid valid Input 1
add_interface_port avalon_streaming_sink data_sink_data data Input 64
add_interface_port avalon_streaming_sink data_sink_empty empty Input 3
add_interface_port avalon_streaming_sink data_sink_error error Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_mux
# | 
add_interface avalon_streaming_sink_mux avalon_streaming end
set_interface_property avalon_streaming_sink_mux associatedClock clk_10g
set_interface_property avalon_streaming_sink_mux associatedReset reset_10g
set_interface_property avalon_streaming_sink_mux dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_mux errorDescriptor ""
set_interface_property avalon_streaming_sink_mux firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_mux maxChannel 1
set_interface_property avalon_streaming_sink_mux readyLatency 0

set_interface_property avalon_streaming_sink_mux ENABLED true

add_interface_port avalon_streaming_sink_mux mux_data_sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink_mux mux_data_sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink_mux mux_data_sink_valid valid Input 1
add_interface_port avalon_streaming_sink_mux mux_data_sink_data data Input 64
add_interface_port avalon_streaming_sink_mux mux_data_sink_empty empty Input 3
add_interface_port avalon_streaming_sink_mux mux_data_sink_error error Input 2
add_interface_port avalon_streaming_sink_mux mux_data_sink_channel channel Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tsu_96b_10g_data_sink
# | 
add_interface tsu_96b_10g_data_sink avalon_streaming end
set_interface_property tsu_96b_10g_data_sink associatedClock clk_10g
set_interface_property tsu_96b_10g_data_sink associatedReset reset_10g
set_interface_property tsu_96b_10g_data_sink dataBitsPerSymbol 96
set_interface_property tsu_96b_10g_data_sink errorDescriptor ""
set_interface_property tsu_96b_10g_data_sink firstSymbolInHighOrderBits true
set_interface_property tsu_96b_10g_data_sink maxChannel 0
set_interface_property tsu_96b_10g_data_sink readyLatency 0

set_interface_property tsu_96b_10g_data_sink ENABLED true

add_interface_port tsu_96b_10g_data_sink tsu_96b_10g_data_sink_valid valid Input 1
add_interface_port tsu_96b_10g_data_sink tsu_96b_10g_data_sink_data data Input 96
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tsu_64b_10g_data_sink
# | 
add_interface tsu_64b_10g_data_sink avalon_streaming end
set_interface_property tsu_64b_10g_data_sink associatedClock clk_10g
set_interface_property tsu_64b_10g_data_sink associatedReset reset_10g
set_interface_property tsu_64b_10g_data_sink dataBitsPerSymbol 64
set_interface_property tsu_64b_10g_data_sink errorDescriptor ""
set_interface_property tsu_64b_10g_data_sink firstSymbolInHighOrderBits true
set_interface_property tsu_64b_10g_data_sink maxChannel 0
set_interface_property tsu_64b_10g_data_sink readyLatency 0

set_interface_property tsu_64b_10g_data_sink ENABLED true

add_interface_port tsu_64b_10g_data_sink tsu_64b_10g_data_sink_valid valid Input 1
add_interface_port tsu_64b_10g_data_sink tsu_64b_10g_data_sink_data data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tsu_96b_1g_data_sink
# | 
add_interface tsu_96b_1g_data_sink avalon_streaming end
set_interface_property tsu_96b_1g_data_sink associatedClock clk_1g
set_interface_property tsu_96b_1g_data_sink associatedReset reset_1g
set_interface_property tsu_96b_1g_data_sink dataBitsPerSymbol 96
set_interface_property tsu_96b_1g_data_sink errorDescriptor ""
set_interface_property tsu_96b_1g_data_sink firstSymbolInHighOrderBits true
set_interface_property tsu_96b_1g_data_sink maxChannel 0
set_interface_property tsu_96b_1g_data_sink readyLatency 0

set_interface_property tsu_96b_1g_data_sink ENABLED true

add_interface_port tsu_96b_1g_data_sink tsu_96b_1g_data_sink_valid valid Input 1
add_interface_port tsu_96b_1g_data_sink tsu_96b_1g_data_sink_data data Input 96
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tsu_64b_1g_data_sink
# | 
add_interface tsu_64b_1g_data_sink avalon_streaming end
set_interface_property tsu_64b_1g_data_sink associatedClock clk_1g
set_interface_property tsu_64b_1g_data_sink associatedReset reset_1g
set_interface_property tsu_64b_1g_data_sink dataBitsPerSymbol 64
set_interface_property tsu_64b_1g_data_sink errorDescriptor ""
set_interface_property tsu_64b_1g_data_sink firstSymbolInHighOrderBits true
set_interface_property tsu_64b_1g_data_sink maxChannel 0
set_interface_property tsu_64b_1g_data_sink readyLatency 0

set_interface_property tsu_64b_1g_data_sink ENABLED true

add_interface_port tsu_64b_1g_data_sink tsu_64b_1g_data_sink_valid valid Input 1
add_interface_port tsu_64b_1g_data_sink tsu_64b_1g_data_sink_data data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point timestamp_fingerprint_96b_data_src
# | 
add_interface timestamp_fingerprint_96b_data_src conduit start
set_interface_assignment timestamp_fingerprint_96b_data_src "ui.blockdiagram.direction" Output
set_interface_property timestamp_fingerprint_96b_data_src ENABLED true

add_interface_port timestamp_fingerprint_96b_data_src timestamp_fingerprint_96b_data_src_valid valid Output 1
add_interface_port timestamp_fingerprint_96b_data_src timestamp_fingerprint_96b_data_src_data_ts data Output 96
add_interface_port timestamp_fingerprint_96b_data_src timestamp_fingerprint_96b_data_src_data_fp fingerprint Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point timestamp_fingerprint_64b_data_src
# | 
add_interface timestamp_fingerprint_64b_data_src conduit start
set_interface_assignment timestamp_fingerprint_64b_data_src "ui.blockdiagram.direction" Output
set_interface_property timestamp_fingerprint_64b_data_src ENABLED true

add_interface_port timestamp_fingerprint_64b_data_src timestamp_fingerprint_64b_data_src_valid valid Output 1
add_interface_port timestamp_fingerprint_64b_data_src timestamp_fingerprint_64b_data_src_data_ts data Output 64
add_interface_port timestamp_fingerprint_64b_data_src timestamp_fingerprint_64b_data_src_data_fp fingerprint Output 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point egress_timestamp_insert_control
# | 
add_interface egress_timestamp_insert_control conduit end
set_interface_assignment egress_timestamp_insert_control "ui.blockdiagram.direction" Input
set_interface_property egress_timestamp_insert_control ENABLED true

add_interface_port egress_timestamp_insert_control etstamp_ins_timestamp_insert timestamp_insert Input 1
add_interface_port egress_timestamp_insert_control etstamp_ins_timestamp_format timestamp_format Input 1

add_interface_port egress_timestamp_insert_control etstamp_ins_residence_time_update residence_time_update Input 1
add_interface_port egress_timestamp_insert_control etstamp_ins_ingress_timestamp_96b ingress_timestamp_96b Input 96
add_interface_port egress_timestamp_insert_control etstamp_ins_ingress_timestamp_64b ingress_timestamp_64b Input 64
add_interface_port egress_timestamp_insert_control etstamp_ins_residence_time_calc_format residence_time_calc_format Input 1

add_interface_port egress_timestamp_insert_control etstamp_ins_checksum_zero checksum_zero Input 1
add_interface_port egress_timestamp_insert_control etstamp_ins_checksum_correct checksum_correct Input 1

add_interface_port egress_timestamp_insert_control etstamp_ins_offset_timestamp offset_timestamp Input 16
add_interface_port egress_timestamp_insert_control etstamp_ins_offset_correction_field offset_correction_field Input 16
add_interface_port egress_timestamp_insert_control etstamp_ins_offset_checksum_field offset_checksum_field Input 16
add_interface_port egress_timestamp_insert_control etstamp_ins_offset_checksum_correction offset_checksum_correction Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point req_ctrl_valid_10g
# | 
add_interface req_ctrl_valid_10g conduit end
set_interface_property req_ctrl_valid_10g associatedClock clk_10g
set_interface_property req_ctrl_valid_10g associatedReset reset_10g
set_interface_property req_ctrl_valid_10g ENABLED true

add_interface_port req_ctrl_valid_10g ptp_inserter_xgmii_valid req_ctrl_valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point req_ctrl_valid_1g
# | 
add_interface req_ctrl_valid_1g conduit end
set_interface_property req_ctrl_valid_1g associatedClock clk_1g
set_interface_property req_ctrl_valid_1g associatedReset reset_1g
set_interface_property req_ctrl_valid_1g ENABLED true

add_interface_port req_ctrl_valid_1g ptp_inserter_gmii_valid req_ctrl_valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point time_stamp_data_10g
# | 
add_interface time_stamp_data_10g conduit end
set_interface_property time_stamp_data_10g associatedClock clk_10g
set_interface_property time_stamp_data_10g associatedReset reset_10g
set_interface_property time_stamp_data_10g ENABLED true

add_interface_port time_stamp_data_10g ptp_inserter_xgmii_egress_timestamp_96b egress_timestamp_96b Output 96
add_interface_port time_stamp_data_10g ptp_inserter_xgmii_ingress_timestamp_96b ingress_timestamp_96b Output 96
add_interface_port time_stamp_data_10g ptp_inserter_xgmii_egress_timestamp_64b egress_timestamp_64b Output 64
add_interface_port time_stamp_data_10g ptp_inserter_xgmii_ingress_timestamp_64b ingress_timestamp_64b Output 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point time_stamp_data_1g
# | 
add_interface time_stamp_data_1g conduit end
set_interface_property time_stamp_data_1g associatedClock clk_1g
set_interface_property time_stamp_data_1g associatedReset reset_1g
set_interface_property time_stamp_data_1g ENABLED true

add_interface_port time_stamp_data_1g ptp_inserter_gmii_egress_timestamp_96b egress_timestamp_96b Output 96
add_interface_port time_stamp_data_1g ptp_inserter_gmii_ingress_timestamp_96b ingress_timestamp_96b Output 96
add_interface_port time_stamp_data_1g ptp_inserter_gmii_egress_timestamp_64b egress_timestamp_64b Output 64
add_interface_port time_stamp_data_1g ptp_inserter_gmii_ingress_timestamp_64b ingress_timestamp_64b Output 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl_signal_10g
# | 
add_interface ctrl_signal_10g conduit end
set_interface_property ctrl_signal_10g associatedClock clk_10g
set_interface_property ctrl_signal_10g associatedReset reset_10g
set_interface_property ctrl_signal_10g ENABLED true

add_interface_port ctrl_signal_10g ptp_inserter_xgmii_timestamp_insert timestamp_insert Output 1
add_interface_port ctrl_signal_10g ptp_inserter_xgmii_residence_time_update residence_time_update Output 1
add_interface_port ctrl_signal_10g ptp_inserter_xgmii_checksum_zero checksum_zero Output 1
add_interface_port ctrl_signal_10g ptp_inserter_xgmii_checksum_correct checksum_correct Output 1
add_interface_port ctrl_signal_10g ptp_inserter_xgmii_residence_time_calc_format residence_time_calc_format Output 1
add_interface_port ctrl_signal_10g ptp_inserter_xgmii_timestamp_format timestamp_format Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl_signal_1g
# | 
add_interface ctrl_signal_1g conduit end
set_interface_property ctrl_signal_1g associatedClock clk_1g
set_interface_property ctrl_signal_1g associatedReset reset_1g
set_interface_property ctrl_signal_1g ENABLED true

add_interface_port ctrl_signal_1g ptp_inserter_gmii_timestamp_insert timestamp_insert Output 1
add_interface_port ctrl_signal_1g ptp_inserter_gmii_residence_time_update residence_time_update Output 1
add_interface_port ctrl_signal_1g ptp_inserter_gmii_checksum_zero checksum_zero Output 1
add_interface_port ctrl_signal_1g ptp_inserter_gmii_checksum_correct checksum_correct Output 1
add_interface_port ctrl_signal_1g ptp_inserter_gmii_residence_time_calc_format residence_time_calc_format Output 1
add_interface_port ctrl_signal_1g ptp_inserter_gmii_timestamp_format timestamp_format Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point octet_location_10g
# | 
add_interface octet_location_10g conduit end
set_interface_property octet_location_10g associatedClock clk_10g
set_interface_property octet_location_10g associatedReset reset_10g
set_interface_property octet_location_10g ENABLED true

add_interface_port octet_location_10g ptp_inserter_xgmii_offset_timestamp offset_timestamp Output 16
add_interface_port octet_location_10g ptp_inserter_xgmii_offset_correction_field offset_correction_field Output 16
add_interface_port octet_location_10g ptp_inserter_xgmii_offset_checksum_field offset_checksum_field Output 16
add_interface_port octet_location_10g ptp_inserter_xgmii_offset_checksum_correction offset_checksum_correction Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point octet_location_1g
# | 
add_interface octet_location_1g conduit end
set_interface_property octet_location_1g associatedClock clk_1g
set_interface_property octet_location_1g associatedReset reset_1g
set_interface_property octet_location_1g ENABLED true

add_interface_port octet_location_1g ptp_inserter_gmii_offset_timestamp offset_timestamp Output 16
add_interface_port octet_location_1g ptp_inserter_gmii_offset_correction_field offset_correction_field Output 16
add_interface_port octet_location_1g ptp_inserter_gmii_offset_checksum_field offset_checksum_field Output 16
add_interface_port octet_location_1g ptp_inserter_gmii_offset_checksum_correction offset_checksum_correction Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point speed_select
# | 
add_interface speed_select conduit end
set_interface_property speed_select ENABLED true
add_interface_port speed_select speed_select export Input 2
# | 
# +-----------------------------------
