# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor __VERSION__
# Fri Oct 09 14:05:33 BST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_usb_debug_link "altera_usb_debug_link" v1.0
# | null 2009.10.09.14:05:29
# | 
# | 
# | D:/work/sopcwire/altera_usb_debug_link.v
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 13.0
# | 
package require -exact qsys 13.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_usb_debug_link
# | 
set_module_property NAME altera_usb_debug_link
set_module_property VERSION 13.1
set_module_property AUTHOR "Altera Corporation"
set_module_property INTERNAL false
set_module_property GROUP "Verification/Debug & Performance"
set_module_property DISPLAY_NAME "USB Debug Link"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK true
set_module_property opaque_address_map false
set_module_property composition_callback compose
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# |
add_parameter DUAL_CLOCK INTEGER 1
set_parameter_property DUAL_CLOCK DISPLAY_NAME "Dual Clocks"
set_parameter_property DUAL_CLOCK ALLOWED_RANGES {"0:No" "1:Yes"}

add_parameter FIFO_DEPTH INTEGER 256
set_parameter_property FIFO_DEPTH DISPLAY_NAME "FIFO Depth"
set_parameter_property FIFO_DEPTH ALLOWED_RANGES {"4:4" "8:8" "16:16" "32:32" "64:64" "128:128" "256:256" "512:512" "1024:1K (1xM9K)" "2048:2K"}

add_parameter CHANNEL_WIDTH INTEGER 8
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME "Channel Width"
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES {"4:21"}

add_parameter MANUAL_DEBUG_FABRIC INTEGER 0
set_parameter_property MANUAL_DEBUG_FABRIC DISPLAY_NAME "Export interfaces for connection to manual debug fabric"
set_parameter_property MANUAL_DEBUG_FABRIC ALLOWED_RANGES {"0:No" "1:Yes"}
# |
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point usb_if
# |
add_interface usb_if conduit end
set_interface_assignment usb_if qsys.ui.export usb
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point debug_clk_in
# | 
add_interface debug_clk_in clock end
set_interface_property debug_clk_in enabled false
# |
# +-----------------------------------

# +-----------------------------------
# | connection point debug_clk
# | 
add_interface debug_clk clock start
# |
# +-----------------------------------

# +-----------------------------------
# | connection point debug_reset
# | 
add_interface debug_reset reset start
# |
# +-----------------------------------

# +-----------------------------------
# | connection point h2t (downstream)
# |
add_interface h2t avalon_streaming start
set_interface_property h2t enabled false
# |
# +-----------------------------------

# +-----------------------------------
# | connection point t2h (upstream)
# | 
add_interface t2h avalon_streaming end
set_interface_property t2h enabled false
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mgmt (downstream)
# |
add_interface mgmt avalon_streaming start
set_interface_property mgmt enabled false
# |
# +-----------------------------------

# +-----------------------------------
# | child instances
# | 
add_instance clock altera_clock_bridge
add_instance reset altera_reset_bridge

add_instance link altera_usb_debug_link_internal
set_interface_property usb_if export_of link.usb_if

set_interface_property debug_clk export_of clock.out_clk
add_connection link.debug_clk clock.in_clk

add_connection link.debug_clk reset.clk
set_interface_property debug_reset export_of reset.out_reset
add_connection link.debug_reset reset.in_reset

# | 
# +-----------------------------------

proc compose {} {
	set dual_clock [get_parameter_value DUAL_CLOCK]
	set fifo_depth [get_parameter_value FIFO_DEPTH]
	set channel_width [get_parameter_value CHANNEL_WIDTH]
	set manual [get_parameter_value MANUAL_DEBUG_FABRIC]

	# Connect clock input if necessary
    if {$dual_clock} {
		set_interface_property debug_clk_in enabled true
    	set_interface_property debug_clk_in export_of link.debug_clk_in
	}

	set_instance_parameter_value link DUAL_CLOCK $dual_clock
	set_instance_parameter_value link FIFO_DEPTH $fifo_depth
	set_instance_parameter_value link CHANNEL_WIDTH $channel_width

	if {$manual} {
		set_interface_property h2t enabled true
		set_interface_property h2t export_of link.h2t
		set_interface_property t2h enabled true
		set_interface_property t2h export_of link.t2h
		set_interface_property mgmt enabled true
		set_interface_property mgmt export_of link.mgmt
	} else {
		add_instance endpoint altera_avalon_st_debug_host_endpoint
		set_instance_parameter_value endpoint CHANNEL_WIDTH $channel_width
		set_instance_parameter_value endpoint NAME "USB"
		set_instance_parameter_value endpoint HOST_PRIORITY 1000
		
		add_connection link.debug_clk endpoint.clk
		add_connection link.debug_reset endpoint.reset
		add_connection link.h2t endpoint.h2t
		add_connection endpoint.t2h link.t2h
		add_connection link.mgmt endpoint.mgmt
	}
}
