# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# $Id: //acds/rel/13.1/ip/merlin/altera_merlin_width_adapter/altera_merlin_width_adapter_hw.tcl#1 $
# $Revision: #1 $
# $Date: 2013/08/11 $
# $Author: swbranch $

# TCL File Generated by Component Editor 9.1
# Wed Mar 11 15:37:00 MYT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_merlin_width_adapter "altera_merlin_width_adapter" v1.0
# | null 2009.03.11.15:37:00
# | 
# | 
# | /build/jyeap/p4root/acds/main/ip/sopc/components/merlin/altera_merlin_width_adapter/altera_merlin_width_adapter.sv
# | 
# |    ./altera_merlin_width_adapter.sv syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package 
# | 
package require -exact qsys 12.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_merlin_width_adapter
# | 
set_module_property NAME altera_merlin_width_adapter
set_module_property VERSION 13.1
set_module_property GROUP "Merlin Components"
set_module_property DISPLAY_NAME "Memory Mapped Width Adapter"
set_module_property DESCRIPTION "Converts between Avalon-MM master and slaves with different data and byte enable widths."
set_module_property AUTHOR "Altera Corporation"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property HIDE_FROM_SOPC true
set_module_property ANALYZE_HDL FALSE
set_module_property DATASHEET_URL http://www.altera.com/literature/hb/qts/qsys_interconnect.pdf
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 

add_fileset synthesis_fileset QUARTUS_SYNTH synth_callback_procedure
set_fileset_property synthesis_fileset TOP_LEVEL altera_merlin_width_adapter 
add_fileset simulation_fileset SIM_VERILOG synth_callback_procedure
set_fileset_property simulation_fileset TOP_LEVEL altera_merlin_width_adapter
add_fileset vhdl_fileset SIM_VHDL synth_callback_procedure_vhdl
set_fileset_property vhdl_fileset TOP_LEVEL altera_merlin_width_adapter

proc synth_callback_procedure { entity_name } {
    add_fileset_file altera_merlin_width_adapter.sv SYSTEM_VERILOG PATH "altera_merlin_width_adapter.sv"
	add_fileset_file altera_merlin_address_alignment.sv SYSTEM_VERILOG PATH "../altera_merlin_axi_master_ni/altera_merlin_address_alignment.sv"
    add_fileset_file altera_merlin_burst_uncompressor.sv SYSTEM_VERILOG PATH "../altera_merlin_slave_agent/altera_merlin_burst_uncompressor.sv"
}

proc synth_callback_procedure_vhdl { entity_name } {
   if {1} {
      add_fileset_file mentor/altera_merlin_width_adapter.sv SYSTEM_VERILOG_ENCRYPT PATH "mentor/altera_merlin_width_adapter.sv" {MENTOR_SPECIFIC}
	  add_fileset_file mentor/altera_merlin_address_alignment.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_axi_master_ni/mentor/altera_merlin_address_alignment.sv" {MENTOR_SPECIFIC}
	  add_fileset_file mentor/altera_merlin_burst_uncompressor.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_slave_agent/mentor/altera_merlin_burst_uncompressor.sv" {MENTOR_SPECIFIC}
   }
   if {1} {
      add_fileset_file aldec/altera_merlin_width_adapter.sv SYSTEM_VERILOG_ENCRYPT PATH "aldec/altera_merlin_width_adapter.sv" {ALDEC_SPECIFIC}
	  add_fileset_file aldec/altera_merlin_address_alignment.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_axi_master_ni/aldec/altera_merlin_address_alignment.sv" {ALDEC_SPECIFIC}
	  add_fileset_file aldec/altera_merlin_burst_uncompressor.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_slave_agent/aldec/altera_merlin_burst_uncompressor.sv" {ALDEC_SPECIFIC}
   }
   if {0} {
      add_fileset_file cadence/altera_merlin_width_adapter.sv SYSTEM_VERILOG_ENCRYPT PATH "cadence/altera_merlin_width_adapter.sv" {CADENCE_SPECIFIC}
	  add_fileset_file cadence/altera_merlin_address_alignment.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_axi_master_ni/cadence/altera_merlin_address_alignment.sv" {CADENCE_SPECIFIC}
	  add_fileset_file cadence/altera_merlin_burst_uncompressor.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_slave_agent/cadence/altera_merlin_burst_uncompressor.sv" {CADENCE_SPECIFIC}
   }
   if {0} {
      add_fileset_file synopsys/altera_merlin_width_adapter.sv SYSTEM_VERILOG_ENCRYPT PATH "synopsys/altera_merlin_width_adapter.sv" {SYNOPSYS_SPECIFIC}
	  add_fileset_file synopsys/altera_merlin_address_alignment.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_axi_master_ni/synopsys/altera_merlin_address_alignment.sv" {SYNOPSYS_SPECIFIC}
	  add_fileset_file synopsys/altera_merlin_burst_uncompressor.sv SYSTEM_VERILOG_ENCRYPT PATH "../altera_merlin_slave_agent/synopsys/altera_merlin_burst_uncompressor.sv" {SYNOPSYS_SPECIFIC}
   }    
}

# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter IN_PKT_ADDR_H INTEGER 60
set_parameter_property IN_PKT_ADDR_H DISPLAY_NAME {Input packet address field index - high}
set_parameter_property IN_PKT_ADDR_H UNITS None
set_parameter_property IN_PKT_ADDR_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_ADDR_H DISPLAY_HINT ""
set_parameter_property IN_PKT_ADDR_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_ADDR_H HDL_PARAMETER true
set_parameter_property IN_PKT_ADDR_H DESCRIPTION {MSB of the input packet address field index}
add_parameter IN_PKT_ADDR_L INTEGER 36
set_parameter_property IN_PKT_ADDR_L DISPLAY_NAME {Input packet address field index - low}
set_parameter_property IN_PKT_ADDR_L UNITS None
set_parameter_property IN_PKT_ADDR_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_ADDR_L DISPLAY_HINT ""
set_parameter_property IN_PKT_ADDR_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_ADDR_L HDL_PARAMETER true
set_parameter_property IN_PKT_ADDR_L DESCRIPTION {LSB of the input packet address field index}
add_parameter IN_PKT_DATA_H INTEGER 31
set_parameter_property IN_PKT_DATA_H DISPLAY_NAME {Input packet data field index - high}
set_parameter_property IN_PKT_DATA_H UNITS None
set_parameter_property IN_PKT_DATA_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_DATA_H DISPLAY_HINT ""
set_parameter_property IN_PKT_DATA_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_DATA_H HDL_PARAMETER true
set_parameter_property IN_PKT_DATA_H DESCRIPTION {MSB of the input packet data field index}
add_parameter IN_PKT_DATA_L INTEGER 0
set_parameter_property IN_PKT_DATA_L DISPLAY_NAME {Input packet data field index - low}
set_parameter_property IN_PKT_DATA_L UNITS None
set_parameter_property IN_PKT_DATA_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_DATA_L DISPLAY_HINT ""
set_parameter_property IN_PKT_DATA_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_DATA_L HDL_PARAMETER true
set_parameter_property IN_PKT_DATA_L DESCRIPTION {LSB of the input packet data field index}
add_parameter IN_PKT_BYTEEN_H INTEGER 35
set_parameter_property IN_PKT_BYTEEN_H DISPLAY_NAME {Input packet byteenable field index - high}
set_parameter_property IN_PKT_BYTEEN_H UNITS None
set_parameter_property IN_PKT_BYTEEN_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BYTEEN_H DISPLAY_HINT ""
set_parameter_property IN_PKT_BYTEEN_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_BYTEEN_H HDL_PARAMETER true
set_parameter_property IN_PKT_BYTEEN_H DESCRIPTION {MSB of the input packet byteenable field index}
add_parameter IN_PKT_BYTEEN_L INTEGER 32
set_parameter_property IN_PKT_BYTEEN_L DISPLAY_NAME {Input packet byteenable field index - low}
set_parameter_property IN_PKT_BYTEEN_L UNITS None
set_parameter_property IN_PKT_BYTEEN_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BYTEEN_L DISPLAY_HINT ""
set_parameter_property IN_PKT_BYTEEN_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_BYTEEN_L HDL_PARAMETER true
set_parameter_property IN_PKT_BYTEEN_L DESCRIPTION {LSB of the input packet byteenable field index}
add_parameter IN_PKT_BYTE_CNT_H INTEGER 63
set_parameter_property IN_PKT_BYTE_CNT_H DISPLAY_NAME {Input packet byte count field index - high}
set_parameter_property IN_PKT_BYTE_CNT_H UNITS None
set_parameter_property IN_PKT_BYTE_CNT_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BYTE_CNT_H DISPLAY_HINT ""
set_parameter_property IN_PKT_BYTE_CNT_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_BYTE_CNT_H HDL_PARAMETER true
set_parameter_property IN_PKT_BYTE_CNT_H DESCRIPTION {MSB of the input packet byte count field index}
add_parameter IN_PKT_BYTE_CNT_L INTEGER 61 
set_parameter_property IN_PKT_BYTE_CNT_L DISPLAY_NAME {Input packet byte count field index - low}
set_parameter_property IN_PKT_BYTE_CNT_L UNITS None
set_parameter_property IN_PKT_BYTE_CNT_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BYTE_CNT_L DISPLAY_HINT ""
set_parameter_property IN_PKT_BYTE_CNT_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_BYTE_CNT_L HDL_PARAMETER true
set_parameter_property IN_PKT_BYTE_CNT_L DESCRIPTION {LSB of the input packet byte count field index}

add_parameter IN_PKT_TRANS_COMPRESSED_READ INTEGER 65
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ DISPLAY_NAME {Input packet compressed read transaction field index}
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ UNITS None
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ DISPLAY_HINT ""
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ HDL_PARAMETER true
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ AFFECTS_GENERATION false
set_parameter_property IN_PKT_TRANS_COMPRESSED_READ DESCRIPTION {Input packet compressed read transaction field index}

add_parameter IN_PKT_BURSTWRAP_H INTEGER 67
set_parameter_property IN_PKT_BURSTWRAP_H DISPLAY_NAME {Input packet burstwrap field index - high}
set_parameter_property IN_PKT_BURSTWRAP_H UNITS None
set_parameter_property IN_PKT_BURSTWRAP_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURSTWRAP_H DISPLAY_HINT ""
set_parameter_property IN_PKT_BURSTWRAP_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURSTWRAP_H HDL_PARAMETER true
set_parameter_property IN_PKT_BURSTWRAP_H DESCRIPTION {MSB of the input packet burstwrap field index}
add_parameter IN_PKT_BURSTWRAP_L INTEGER 66 
set_parameter_property IN_PKT_BURSTWRAP_L DISPLAY_NAME {Input packet burstwrap field index - low}
set_parameter_property IN_PKT_BURSTWRAP_L UNITS None
set_parameter_property IN_PKT_BURSTWRAP_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURSTWRAP_L DISPLAY_HINT ""
set_parameter_property IN_PKT_BURSTWRAP_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURSTWRAP_L HDL_PARAMETER true
set_parameter_property IN_PKT_BURSTWRAP_L DESCRIPTION {LSB of the input packet burstwrap field index}

add_parameter IN_PKT_BURST_SIZE_H INTEGER 70
set_parameter_property IN_PKT_BURST_SIZE_H DISPLAY_NAME {Input packet burst size field index - high}
set_parameter_property IN_PKT_BURST_SIZE_H UNITS None
set_parameter_property IN_PKT_BURST_SIZE_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURST_SIZE_H DISPLAY_HINT ""
set_parameter_property IN_PKT_BURST_SIZE_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURST_SIZE_H HDL_PARAMETER true
set_parameter_property IN_PKT_BURST_SIZE_H DESCRIPTION {MSB of the input packet burst size field index}
add_parameter IN_PKT_BURST_SIZE_L INTEGER 68 
set_parameter_property IN_PKT_BURST_SIZE_L DISPLAY_NAME {Input packet burst size field index - low}
set_parameter_property IN_PKT_BURST_SIZE_L UNITS None
set_parameter_property IN_PKT_BURST_SIZE_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURST_SIZE_L DISPLAY_HINT ""
set_parameter_property IN_PKT_BURST_SIZE_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURST_SIZE_L HDL_PARAMETER true
set_parameter_property IN_PKT_BURST_SIZE_L DESCRIPTION {LSB of the input packet burst size field index}

add_parameter IN_PKT_RESPONSE_STATUS_H INTEGER 72
set_parameter_property IN_PKT_RESPONSE_STATUS_H DISPLAY_NAME {Input packet response status field index - high}
set_parameter_property IN_PKT_RESPONSE_STATUS_H UNITS None
set_parameter_property IN_PKT_RESPONSE_STATUS_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_RESPONSE_STATUS_H DISPLAY_HINT ""
set_parameter_property IN_PKT_RESPONSE_STATUS_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_RESPONSE_STATUS_H HDL_PARAMETER true
set_parameter_property IN_PKT_RESPONSE_STATUS_H DESCRIPTION {MSB of the input packet response status field index}
add_parameter IN_PKT_RESPONSE_STATUS_L INTEGER 71 
set_parameter_property IN_PKT_RESPONSE_STATUS_L DISPLAY_NAME {Input packet response status field index - low}
set_parameter_property IN_PKT_RESPONSE_STATUS_L UNITS None
set_parameter_property IN_PKT_RESPONSE_STATUS_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_RESPONSE_STATUS_L DISPLAY_HINT ""
set_parameter_property IN_PKT_RESPONSE_STATUS_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_RESPONSE_STATUS_L HDL_PARAMETER true
set_parameter_property IN_PKT_RESPONSE_STATUS_L DESCRIPTION {LSB of the input packet response status field index}
add_parameter IN_PKT_TRANS_EXCLUSIVE INTEGER 73 
set_parameter_property IN_PKT_TRANS_EXCLUSIVE DISPLAY_NAME {Input packet exclusive trans field }
set_parameter_property IN_PKT_TRANS_EXCLUSIVE UNITS None
set_parameter_property IN_PKT_TRANS_EXCLUSIVE ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_TRANS_EXCLUSIVE DISPLAY_HINT ""
set_parameter_property IN_PKT_TRANS_EXCLUSIVE AFFECTS_GENERATION false
set_parameter_property IN_PKT_TRANS_EXCLUSIVE HDL_PARAMETER true
set_parameter_property IN_PKT_TRANS_EXCLUSIVE DESCRIPTION {the input packet exclusive trans field index}

add_parameter IN_PKT_BURST_TYPE_H INTEGER 75
set_parameter_property IN_PKT_BURST_TYPE_H DISPLAY_NAME {Input packet burst type field index - high}
set_parameter_property IN_PKT_BURST_TYPE_H UNITS None
set_parameter_property IN_PKT_BURST_TYPE_H ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURST_TYPE_H DISPLAY_HINT ""
set_parameter_property IN_PKT_BURST_TYPE_H AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURST_TYPE_H HDL_PARAMETER true
set_parameter_property IN_PKT_BURST_TYPE_H DESCRIPTION {MSB of the input packet burst type field index}
add_parameter IN_PKT_BURST_TYPE_L INTEGER 74 
set_parameter_property IN_PKT_BURST_TYPE_L DISPLAY_NAME {Input packet burst type field index - low}
set_parameter_property IN_PKT_BURST_TYPE_L UNITS None
set_parameter_property IN_PKT_BURST_TYPE_L ALLOWED_RANGES 0:2147483647
set_parameter_property IN_PKT_BURST_TYPE_L DISPLAY_HINT ""
set_parameter_property IN_PKT_BURST_TYPE_L AFFECTS_GENERATION false
set_parameter_property IN_PKT_BURST_TYPE_L HDL_PARAMETER true
set_parameter_property IN_PKT_BURST_TYPE_L DESCRIPTION {LSB of the input packet burst type field index}

add_parameter IN_PKT_ORI_BURST_SIZE_L INTEGER 110
set_parameter_property IN_PKT_ORI_BURST_SIZE_L DISPLAY_NAME "Packet original burst size index - low"
set_parameter_property IN_PKT_ORI_BURST_SIZE_L TYPE INTEGER
set_parameter_property IN_PKT_ORI_BURST_SIZE_L UNITS None
set_parameter_property IN_PKT_ORI_BURST_SIZE_L DESCRIPTION "LSB of the packet original burst size field index"
set_parameter_property IN_PKT_ORI_BURST_SIZE_L AFFECTS_ELABORATION true
set_parameter_property IN_PKT_ORI_BURST_SIZE_L HDL_PARAMETER true
add_parameter IN_PKT_ORI_BURST_SIZE_H INTEGER 113
set_parameter_property IN_PKT_ORI_BURST_SIZE_H DISPLAY_NAME "Packet original burst size index - high"
set_parameter_property IN_PKT_ORI_BURST_SIZE_H TYPE INTEGER
set_parameter_property IN_PKT_ORI_BURST_SIZE_H UNITS None
set_parameter_property IN_PKT_ORI_BURST_SIZE_H DESCRIPTION "MSB of the packet original burst size field index"
set_parameter_property IN_PKT_ORI_BURST_SIZE_H AFFECTS_ELABORATION true
set_parameter_property IN_PKT_ORI_BURST_SIZE_H HDL_PARAMETER true

add_parameter IN_ST_DATA_W INTEGER 76
set_parameter_property IN_ST_DATA_W DISPLAY_NAME {Input data width}
set_parameter_property IN_ST_DATA_W UNITS None
set_parameter_property IN_ST_DATA_W ALLOWED_RANGES 0:2147483647
set_parameter_property IN_ST_DATA_W DISPLAY_HINT ""
set_parameter_property IN_ST_DATA_W AFFECTS_GENERATION false
set_parameter_property IN_ST_DATA_W HDL_PARAMETER true
set_parameter_property IN_ST_DATA_W DESCRIPTION {Input packet data width}

add_parameter OUT_PKT_ADDR_H INTEGER 60
set_parameter_property OUT_PKT_ADDR_H DISPLAY_NAME {Output packet address field index - high}
set_parameter_property OUT_PKT_ADDR_H UNITS None
set_parameter_property OUT_PKT_ADDR_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_ADDR_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_ADDR_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_ADDR_H HDL_PARAMETER true
set_parameter_property OUT_PKT_ADDR_H DESCRIPTION {MSB of the output packet address field index}
add_parameter OUT_PKT_ADDR_L INTEGER 36
set_parameter_property OUT_PKT_ADDR_L DISPLAY_NAME {Output packet address field index - low}
set_parameter_property OUT_PKT_ADDR_L UNITS None
set_parameter_property OUT_PKT_ADDR_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_ADDR_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_ADDR_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_ADDR_L HDL_PARAMETER true
set_parameter_property OUT_PKT_ADDR_L DESCRIPTION {LSB of the output packet address field index}
add_parameter OUT_PKT_DATA_H INTEGER 31
set_parameter_property OUT_PKT_DATA_H DISPLAY_NAME {Output packet byteenable field index - high}
set_parameter_property OUT_PKT_DATA_H UNITS None
set_parameter_property OUT_PKT_DATA_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_DATA_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_DATA_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_DATA_H HDL_PARAMETER true
set_parameter_property OUT_PKT_DATA_H DESCRIPTION {MSB of the output packet byteenable field index}
add_parameter OUT_PKT_DATA_L INTEGER 0
set_parameter_property OUT_PKT_DATA_L DISPLAY_NAME {Output packet byteenable field index - low}
set_parameter_property OUT_PKT_DATA_L UNITS None
set_parameter_property OUT_PKT_DATA_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_DATA_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_DATA_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_DATA_L HDL_PARAMETER true
set_parameter_property OUT_PKT_DATA_L DESCRIPTION {LSB of the output packet byteenable field index}
add_parameter OUT_PKT_BYTEEN_H INTEGER 35
set_parameter_property OUT_PKT_BYTEEN_H DISPLAY_NAME {Output packet byte count field index - high}
set_parameter_property OUT_PKT_BYTEEN_H UNITS None
set_parameter_property OUT_PKT_BYTEEN_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BYTEEN_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_BYTEEN_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BYTEEN_H HDL_PARAMETER true
set_parameter_property OUT_PKT_BYTEEN_H DESCRIPTION {MSB of the output packet byte count field index}
add_parameter OUT_PKT_BYTEEN_L INTEGER 32
set_parameter_property OUT_PKT_BYTEEN_L DISPLAY_NAME {Output packet byte count field index - low}
set_parameter_property OUT_PKT_BYTEEN_L UNITS None
set_parameter_property OUT_PKT_BYTEEN_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BYTEEN_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_BYTEEN_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BYTEEN_L HDL_PARAMETER true
set_parameter_property OUT_PKT_BYTEEN_L DESCRIPTION {LSB of the output packet byte count field index}
add_parameter OUT_PKT_BYTE_CNT_H INTEGER 63 
set_parameter_property OUT_PKT_BYTE_CNT_H DISPLAY_NAME {Output packet burstwrap field index - high}
set_parameter_property OUT_PKT_BYTE_CNT_H UNITS None
set_parameter_property OUT_PKT_BYTE_CNT_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BYTE_CNT_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_BYTE_CNT_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BYTE_CNT_H HDL_PARAMETER true
set_parameter_property OUT_PKT_BYTE_CNT_H DESCRIPTION {MSB of the output packet burstwrap field index}
add_parameter OUT_PKT_BYTE_CNT_L INTEGER 61
set_parameter_property OUT_PKT_BYTE_CNT_L DISPLAY_NAME {Output packet burstwrap field index - low}
set_parameter_property OUT_PKT_BYTE_CNT_L UNITS None
set_parameter_property OUT_PKT_BYTE_CNT_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BYTE_CNT_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_BYTE_CNT_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BYTE_CNT_L HDL_PARAMETER true
set_parameter_property OUT_PKT_BYTE_CNT_L DESCRIPTION {LSB of the output packet burstwrap field index}

add_parameter OUT_PKT_TRANS_COMPRESSED_READ INTEGER 65
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ DISPLAY_NAME {Output packet data field index - high}
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ UNITS None
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ AFFECTS_GENERATION false
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ DISPLAY_HINT ""
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ HDL_PARAMETER true
set_parameter_property OUT_PKT_TRANS_COMPRESSED_READ DESCRIPTION {MSB of the output packet data field index}
add_parameter OUT_PKT_BURST_SIZE_H INTEGER 68
set_parameter_property OUT_PKT_BURST_SIZE_H DISPLAY_NAME {Output packet burst size field index - high}
set_parameter_property OUT_PKT_BURST_SIZE_H UNITS None
set_parameter_property OUT_PKT_BURST_SIZE_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BURST_SIZE_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_BURST_SIZE_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BURST_SIZE_H HDL_PARAMETER true
set_parameter_property OUT_PKT_BURST_SIZE_H DESCRIPTION {MSB of the Output packet burst size field index}
add_parameter OUT_PKT_BURST_SIZE_L INTEGER 66 
set_parameter_property OUT_PKT_BURST_SIZE_L DISPLAY_NAME {Output packet burst size field index - low}
set_parameter_property OUT_PKT_BURST_SIZE_L UNITS None
set_parameter_property OUT_PKT_BURST_SIZE_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BURST_SIZE_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_BURST_SIZE_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BURST_SIZE_L HDL_PARAMETER true
set_parameter_property OUT_PKT_BURST_SIZE_L DESCRIPTION {LSB of the Output packet burst size field index}

add_parameter OUT_PKT_RESPONSE_STATUS_H INTEGER 70
set_parameter_property OUT_PKT_RESPONSE_STATUS_H DISPLAY_NAME {Output packet response status field index - high}
set_parameter_property OUT_PKT_RESPONSE_STATUS_H UNITS None
set_parameter_property OUT_PKT_RESPONSE_STATUS_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_RESPONSE_STATUS_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_RESPONSE_STATUS_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_RESPONSE_STATUS_H HDL_PARAMETER true
set_parameter_property OUT_PKT_RESPONSE_STATUS_H DESCRIPTION {MSB of the Output packet response status field index}
add_parameter OUT_PKT_RESPONSE_STATUS_L INTEGER 69 
set_parameter_property OUT_PKT_RESPONSE_STATUS_L DISPLAY_NAME {Output packet response status field index - low}
set_parameter_property OUT_PKT_RESPONSE_STATUS_L UNITS None
set_parameter_property OUT_PKT_RESPONSE_STATUS_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_RESPONSE_STATUS_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_RESPONSE_STATUS_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_RESPONSE_STATUS_L HDL_PARAMETER true
set_parameter_property OUT_PKT_RESPONSE_STATUS_L DESCRIPTION {LSB of the Output packet response status field index}


add_parameter OUT_PKT_TRANS_EXCLUSIVE INTEGER 71 
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE DISPLAY_NAME {Output packet exclusive trans field }
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE UNITS None
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE DISPLAY_HINT ""
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE AFFECTS_GENERATION false
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE HDL_PARAMETER true
set_parameter_property OUT_PKT_TRANS_EXCLUSIVE DESCRIPTION {the Output packet exclusive trans field index}

add_parameter OUT_PKT_BURST_TYPE_H INTEGER 73
set_parameter_property OUT_PKT_BURST_TYPE_H DISPLAY_NAME {Input packet burst type field index - high}
set_parameter_property OUT_PKT_BURST_TYPE_H UNITS None
set_parameter_property OUT_PKT_BURST_TYPE_H ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BURST_TYPE_H DISPLAY_HINT ""
set_parameter_property OUT_PKT_BURST_TYPE_H AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BURST_TYPE_H HDL_PARAMETER true
set_parameter_property OUT_PKT_BURST_TYPE_H DESCRIPTION {MSB of the input packet burst type field index}

add_parameter OUT_PKT_BURST_TYPE_L INTEGER 72 
set_parameter_property OUT_PKT_BURST_TYPE_L DISPLAY_NAME {Input packet burst type field index - low}
set_parameter_property OUT_PKT_BURST_TYPE_L UNITS None
set_parameter_property OUT_PKT_BURST_TYPE_L ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_PKT_BURST_TYPE_L DISPLAY_HINT ""
set_parameter_property OUT_PKT_BURST_TYPE_L AFFECTS_GENERATION false
set_parameter_property OUT_PKT_BURST_TYPE_L HDL_PARAMETER true
set_parameter_property OUT_PKT_BURST_TYPE_L DESCRIPTION {LSB of the input packet burst type field index}

add_parameter OUT_PKT_ORI_BURST_SIZE_L INTEGER 110
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L DISPLAY_NAME "Packet original burst size index - low"
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L TYPE INTEGER
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L UNITS None
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L DESCRIPTION "LSB of the packet original burst size field index"
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L AFFECTS_ELABORATION true
set_parameter_property OUT_PKT_ORI_BURST_SIZE_L HDL_PARAMETER true
add_parameter OUT_PKT_ORI_BURST_SIZE_H INTEGER 113
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H DISPLAY_NAME "Packet original burst size index - high"
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H TYPE INTEGER
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H UNITS None
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H DESCRIPTION "MSB of the packet original burst size field index"
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H AFFECTS_ELABORATION true
set_parameter_property OUT_PKT_ORI_BURST_SIZE_H HDL_PARAMETER true

add_parameter OUT_ST_DATA_W INTEGER 74
set_parameter_property OUT_ST_DATA_W DISPLAY_NAME {Output packet data field index - low}
set_parameter_property OUT_ST_DATA_W UNITS None
set_parameter_property OUT_ST_DATA_W ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_ST_DATA_W DISPLAY_HINT ""
set_parameter_property OUT_ST_DATA_W AFFECTS_GENERATION false
set_parameter_property OUT_ST_DATA_W HDL_PARAMETER true
set_parameter_property OUT_ST_DATA_W DESCRIPTION {LSB of the output packet data field index}
add_parameter ST_CHANNEL_W INTEGER 32
set_parameter_property ST_CHANNEL_W DISPLAY_NAME {Streaming channel width}
set_parameter_property ST_CHANNEL_W UNITS None
set_parameter_property ST_CHANNEL_W ALLOWED_RANGES 0:2147483647
set_parameter_property ST_CHANNEL_W DISPLAY_HINT ""
set_parameter_property ST_CHANNEL_W AFFECTS_GENERATION false
set_parameter_property ST_CHANNEL_W HDL_PARAMETER true
set_parameter_property ST_CHANNEL_W DESCRIPTION {Streaming channel width}
add_parameter OPTIMIZE_FOR_RSP INTEGER 0
set_parameter_property OPTIMIZE_FOR_RSP UNITS None
set_parameter_property OPTIMIZE_FOR_RSP ALLOWED_RANGES 0:1
set_parameter_property OPTIMIZE_FOR_RSP DISPLAY_HINT ""
set_parameter_property OPTIMIZE_FOR_RSP AFFECTS_GENERATION false
set_parameter_property OPTIMIZE_FOR_RSP HDL_PARAMETER true
set_parameter_property OPTIMIZE_FOR_RSP DESCRIPTION {Implement an optimization for non-bursting wide-to-narrow responses}
set_parameter_property OPTIMIZE_FOR_RSP DISPLAY_NAME {Optimize for response}

add_parameter RESPONSE_PATH INTEGER 0
set_parameter_property RESPONSE_PATH UNITS None
set_parameter_property RESPONSE_PATH ALLOWED_RANGES 0:1
set_parameter_property RESPONSE_PATH DISPLAY_HINT ""
set_parameter_property RESPONSE_PATH AFFECTS_GENERATION false
set_parameter_property RESPONSE_PATH HDL_PARAMETER true
set_parameter_property RESPONSE_PATH DESCRIPTION {Identifies if a width adapter is used on the response path}
set_parameter_property RESPONSE_PATH DISPLAY_NAME {Response width adapter}   

add_parameter CONSTANT_BURST_SIZE INTEGER 1
set_parameter_property CONSTANT_BURST_SIZE UNITS None
set_parameter_property CONSTANT_BURST_SIZE ALLOWED_RANGES 0:1
set_parameter_property CONSTANT_BURST_SIZE DISPLAY_HINT ""
set_parameter_property CONSTANT_BURST_SIZE AFFECTS_GENERATION false
set_parameter_property CONSTANT_BURST_SIZE HDL_PARAMETER true
set_parameter_property CONSTANT_BURST_SIZE DESCRIPTION {Identifies if system only have constant burst size (Avalon only)}
set_parameter_property CONSTANT_BURST_SIZE DISPLAY_NAME {System only have constant burst size}   

add_parameter PACKING INTEGER 1
set_parameter_property PACKING UNITS None
set_parameter_property PACKING ALLOWED_RANGES 0:1
set_parameter_property PACKING DISPLAY_HINT ""
set_parameter_property PACKING AFFECTS_GENERATION false
set_parameter_property PACKING HDL_PARAMETER true
set_parameter_property PACKING DESCRIPTION {Identifies if adapter does packing for Narrow-to-Wide or not}
set_parameter_property PACKING DISPLAY_NAME {Narrow-to-Wide packing}   

add_parameter IN_MERLIN_PACKET_FORMAT String ""
set_parameter_property IN_MERLIN_PACKET_FORMAT DISPLAY_NAME {Input Merlin packet format descriptor}
set_parameter_property IN_MERLIN_PACKET_FORMAT UNITS None
set_parameter_property IN_MERLIN_PACKET_FORMAT DESCRIPTION {Input Merlin packet format descriptor}

add_parameter OUT_MERLIN_PACKET_FORMAT String ""
set_parameter_property OUT_MERLIN_PACKET_FORMAT DISPLAY_NAME {Merlin packet format descriptor - output}
set_parameter_property OUT_MERLIN_PACKET_FORMAT UNITS None
set_parameter_property OUT_MERLIN_PACKET_FORMAT DESCRIPTION {Merlin packet format descriptor - output}

add_parameter COMMAND_SIZE_W INTEGER 3
set_parameter_property COMMAND_SIZE_W DISPLAY_NAME {Command-size input width}
set_parameter_property COMMAND_SIZE_W UNITS None
set_parameter_property COMMAND_SIZE_W ALLOWED_RANGES 0:2147483647
set_parameter_property COMMAND_SIZE_W DISPLAY_HINT ""
set_parameter_property COMMAND_SIZE_W AFFECTS_GENERATION false
set_parameter_property COMMAND_SIZE_W HDL_PARAMETER FALSE
set_parameter_property COMMAND_SIZE_W DESCRIPTION {The Width of input command-size}
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF true

add_interface_port clk clk clk Input 1
add_interface_port clk reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point command size sink
# | 
add_interface command_size_sink avalon_streaming end
set_interface_property command_size_sink dataBitsPerSymbol 64
set_interface_property command_size_sink errorDescriptor ""
set_interface_property command_size_sink maxChannel 0
set_interface_property command_size_sink readyLatency 0
set_interface_property command_size_sink symbolsPerBeat 1

set_interface_property command_size_sink ASSOCIATED_CLOCK clk
set_interface_property command_size_sink ENABLED true
set_interface_property command_size_sink EXPORT_OF true

add_interface_port command_size_sink in_command_size_data data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sink
# | 
add_interface sink avalon_streaming end
set_interface_property sink dataBitsPerSymbol 64
set_interface_property sink errorDescriptor ""
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink symbolsPerBeat 1

set_interface_property sink ASSOCIATED_CLOCK clk
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF true

add_interface_port sink in_valid valid Input 1
add_interface_port sink in_channel channel Input 1
add_interface_port sink in_startofpacket startofpacket Input 1
add_interface_port sink in_endofpacket endofpacket Input 1
add_interface_port sink in_ready ready Output 1
add_interface_port sink in_data data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point src
# | 
add_interface src avalon_streaming start
set_interface_property src dataBitsPerSymbol 64
set_interface_property src errorDescriptor ""
set_interface_property src maxChannel 0
set_interface_property src readyLatency 0
set_interface_property src symbolsPerBeat 1

set_interface_property src ASSOCIATED_CLOCK clk
set_interface_property src ENABLED true
set_interface_property src EXPORT_OF true

add_interface_port src out_endofpacket endofpacket Output 1
add_interface_port src out_data data Output 64
add_interface_port src out_channel channel Output 1
add_interface_port src out_valid valid Output 1
add_interface_port src out_ready ready Input 1
add_interface_port src out_startofpacket startofpacket Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration callback
# +-----------------------------------
proc elaborate {} {

    set in_st_data_width  [ get_parameter_value IN_ST_DATA_W  ]
    set out_st_data_width [ get_parameter_value OUT_ST_DATA_W ]
    set st_chan_width     [ get_parameter_value ST_CHANNEL_W  ]
    set in_fields         [ get_parameter_value IN_MERLIN_PACKET_FORMAT ]
    set out_fields        [ get_parameter_value OUT_MERLIN_PACKET_FORMAT ]
    set command_size_width  [ get_parameter_value COMMAND_SIZE_W ]

    # Terminate all these in_command_size port as avalon default wont use the,
	# We only need these ports in response width adapter in "combined width adapter"
	
    set_port_property in_command_size_data  TERMINATION true
	set_port_property  in_command_size_data vhdl_type std_logic_vector
	set_interface_property command_size_sink  dataBitsPerSymbol $command_size_width
    set_port_property in_command_size_data  WIDTH_EXPR $command_size_width

    set_interface_property src  dataBitsPerSymbol $out_st_data_width
    set_interface_property sink dataBitsPerSymbol $in_st_data_width

    set_port_property in_data  WIDTH_EXPR $in_st_data_width
	set_port_property  in_data vhdl_type std_logic_vector
    set_port_property out_data WIDTH_EXPR $out_st_data_width
	set_port_property  out_data vhdl_type std_logic_vector

    set_interface_assignment sink merlin.packet_format $in_fields
    set_interface_assignment src merlin.packet_format $out_fields

    set_interface_assignment sink merlin.flow.src src

    set_port_property in_channel  WIDTH_EXPR $st_chan_width
	set_port_property  in_channel vhdl_type std_logic_vector
    set_port_property out_channel WIDTH_EXPR $st_chan_width
	set_port_property  out_channel vhdl_type std_logic_vector
}

