# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 12.1
# Mon Dec 03 17:41:50 MYT 2012
# DO NOT MODIFY


# 
# altera_eth_gmii_mii_encoder "altera_eth_gmii_mii_encoder" v1.0
# null 2012.12.03.17:41:50
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module altera_eth_gmii_mii_encoder
# 
set_module_property NAME altera_eth_gmii_mii_encoder
set_module_property VERSION 13.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Ethernet/Submodules"
set_module_property DISPLAY_NAME altera_eth_gmii_mii_encoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property ELABORATION_CALLBACK elaborate
set_module_property EDITABLE true
set_module_property ANALYZE_HDL false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH q_synth ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_eth_gmii_mii_encoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false

proc q_synth {name} {
    set enable_timestamping [ get_parameter_value ENABLE_TIMESTAMPING ]
    set enable_ptp_1step [ get_parameter_value ENABLE_PTP_1STEP ]
    
    add_fileset_file altera_eth_gmii_mii_encoder.v VERILOG PATH altera_eth_gmii_mii_encoder.v
    add_fileset_file altera_eth_gmii_mii_encoder_tx_if.v VERILOG PATH altera_eth_gmii_mii_encoder_tx_if.v
    add_fileset_file altera_eth_gmii_encoder_dfa.v VERILOG PATH altera_eth_gmii_encoder_dfa.v
    add_fileset_file altera_eth_gmii_encoder.v VERILOG PATH altera_eth_gmii_encoder.v
    
    if {$enable_timestamping} {
        add_fileset_file altera_tse_gmii_to_avst_if.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii2avst_converter/altera_tse_gmii_to_avst_if.v"
        add_fileset_file altera_tse_tsu.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/altera_tse_tsu.v"
        add_fileset_file altera_tse_tsu.ocp OTHER PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/altera_tse_tsu.ocp"
    }
    
    if {$enable_ptp_1step} {
        add_fileset_file altera_tse_ptp_inserter.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/altera_tse_ptp_inserter.v"
        add_fileset_file altera_tse_ptp_inserter.ocp OTHER PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/altera_tse_ptp_inserter.ocp"
        add_fileset_file altera_tse_crc328generator.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/altera_tse_crc328generator.v"
        add_fileset_file altera_tse_crc32ctl8.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/altera_tse_crc32ctl8.v"
        add_fileset_file altera_tse_crc32galois8.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/altera_tse_crc32galois8.v"
        add_fileset_file altera_tse_ptp_1588_crc.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/altera_tse_ptp_1588_crc.v"
        add_fileset_file altera_tse_ptp_1588_crc.ocp OTHER PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/altera_tse_ptp_1588_crc.ocp"
        add_fileset_file altera_tse_avst_to_gmii_if.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_avst2gmii_converter/altera_tse_avst_to_gmii_if.v"
    }
}

add_fileset_file altera_avalon_dc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_dc_fifo/altera_avalon_dc_fifo.v"
add_fileset_file altera_dcfifo_synchronizer_bundle.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_dc_fifo/altera_dcfifo_synchronizer_bundle.v"



# -----------------------------------
# IEEE encryption
# ----------------------------------- 
set HDL_LIB_DIR "../lib"

add_fileset simulation_verilog SIM_VERILOG sim_ver ""
set_fileset_property simulation_verilog TOP_LEVEL altera_eth_gmii_mii_encoder
set_fileset_property simulation_verilog ENABLE_RELATIVE_INCLUDE_PATHS false

add_fileset simulation_vhdl SIM_VHDL sim_ver ""
set_fileset_property simulation_vhdl TOP_LEVEL altera_eth_gmii_mii_encoder
set_fileset_property simulation_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false



proc sim_ver {name} {
    set enable_timestamping [ get_parameter_value ENABLE_TIMESTAMPING ]
    set enable_ptp_1step [ get_parameter_value ENABLE_PTP_1STEP ]
    
    if {1} {
        add_fileset_file mentor/altera_eth_gmii_mii_encoder.v SYSTEM_VERILOG_ENCRYPT PATH "mentor/altera_eth_gmii_mii_encoder.v" {MENTOR_SPECIFIC}
        add_fileset_file mentor/altera_eth_gmii_mii_encoder_tx_if.v SYSTEM_VERILOG_ENCRYPT PATH "mentor/altera_eth_gmii_mii_encoder_tx_if.v" {MENTOR_SPECIFIC}
        add_fileset_file mentor/altera_eth_gmii_encoder_dfa.v VERILOG_ENCRYPT PATH "mentor/altera_eth_gmii_encoder_dfa.v" {MENTOR_SPECIFIC}
        add_fileset_file mentor/altera_eth_gmii_encoder.v VERILOG_ENCRYPT PATH "mentor/altera_eth_gmii_encoder.v" {MENTOR_SPECIFIC}
        if {$enable_timestamping} {
            add_fileset_file mentor/altera_tse_gmii_to_avst_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii2avst_converter/mentor/altera_tse_gmii_to_avst_if.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_tsu.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/mentor/altera_tse_tsu.v" {MENTOR_SPECIFIC}
        }
        if {$enable_ptp_1step} {
            add_fileset_file mentor/altera_tse_ptp_inserter.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/mentor/altera_tse_ptp_inserter.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_crc328generator.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/mentor/altera_tse_crc328generator.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_crc32ctl8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/mentor/altera_tse_crc32ctl8.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_crc32galois8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/mentor/altera_tse_crc32galois8.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_ptp_1588_crc.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/mentor/altera_tse_ptp_1588_crc.v" {MENTOR_SPECIFIC}
            add_fileset_file mentor/altera_tse_avst_to_gmii_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_avst2gmii_converter/mentor/altera_tse_avst_to_gmii_if.v" {MENTOR_SPECIFIC}
        }
    }
    if {1} {                
        add_fileset_file aldec/altera_eth_gmii_mii_encoder.v SYSTEM_VERILOG_ENCRYPT PATH "aldec/altera_eth_gmii_mii_encoder.v" {ALDEC_SPECIFIC}
        add_fileset_file aldec/altera_eth_gmii_mii_encoder_tx_if.v SYSTEM_VERILOG_ENCRYPT PATH "aldec/altera_eth_gmii_mii_encoder_tx_if.v" {ALDEC_SPECIFIC}
        add_fileset_file aldec/altera_eth_gmii_encoder_dfa.v VERILOG_ENCRYPT PATH "aldec/altera_eth_gmii_encoder_dfa.v" {ALDEC_SPECIFIC}
        add_fileset_file aldec/altera_eth_gmii_encoder.v VERILOG_ENCRYPT PATH "aldec/altera_eth_gmii_encoder.v" {ALDEC_SPECIFIC}
        if {$enable_timestamping} {
            add_fileset_file aldec/altera_tse_gmii_to_avst_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii2avst_converter/aldec/altera_tse_gmii_to_avst_if.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_tsu.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/aldec/altera_tse_tsu.v" {ALDEC_SPECIFIC}
        }
        if {$enable_ptp_1step} {
            add_fileset_file aldec/altera_tse_ptp_inserter.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/aldec/altera_tse_ptp_inserter.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_crc328generator.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/aldec/altera_tse_crc328generator.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_crc32ctl8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/aldec/altera_tse_crc32ctl8.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_crc32galois8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/aldec/altera_tse_crc32galois8.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_ptp_1588_crc.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/aldec/altera_tse_ptp_1588_crc.v" {ALDEC_SPECIFIC}
            add_fileset_file aldec/altera_tse_avst_to_gmii_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_avst2gmii_converter/aldec/altera_tse_avst_to_gmii_if.v" {ALDEC_SPECIFIC}
        }
    }
    if {0} {
        add_fileset_file cadence/altera_eth_gmii_mii_encoder.v SYSTEM_VERILOG_ENCRYPT PATH "cadence/altera_eth_gmii_mii_encoder.v" {CADENCE_SPECIFIC}
        add_fileset_file cadence/altera_eth_gmii_mii_encoder_tx_if.v SYSTEM_VERILOG_ENCRYPT PATH "cadence/altera_eth_gmii_mii_encoder_tx_if.v" {CADENCE_SPECIFIC}
        add_fileset_file cadence/altera_eth_gmii_encoder_dfa.v VERILOG_ENCRYPT PATH "cadence/altera_eth_gmii_encoder_dfa.v" {CADENCE_SPECIFIC}
        add_fileset_file cadence/altera_eth_gmii_encoder.v VERILOG_ENCRYPT PATH "cadence/altera_eth_gmii_encoder.v" {CADENCE_SPECIFIC}
        if {$enable_timestamping} {
            add_fileset_file cadence/altera_tse_gmii_to_avst_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii2avst_converter/cadence/altera_tse_gmii_to_avst_if.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_tsu.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/cadence/altera_tse_tsu.v" {CADENCE_SPECIFIC}
        }
        if {$enable_ptp_1step} {
            add_fileset_file cadence/altera_tse_ptp_inserter.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/cadence/altera_tse_ptp_inserter.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_crc328generator.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/cadence/altera_tse_crc328generator.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_crc32ctl8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/cadence/altera_tse_crc32ctl8.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_crc32galois8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/cadence/altera_tse_crc32galois8.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_ptp_1588_crc.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/cadence/altera_tse_ptp_1588_crc.v" {CADENCE_SPECIFIC}
            add_fileset_file cadence/altera_tse_avst_to_gmii_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_avst2gmii_converter/cadence/altera_tse_avst_to_gmii_if.v" {CADENCE_SPECIFIC}
        }
    }
    if {0} {
        add_fileset_file synopsys/altera_eth_gmii_mii_encoder.v SYSTEM_VERILOG_ENCRYPT PATH "synopsys/altera_eth_gmii_mii_encoder.v" {SYNOPSYS_SPECIFIC}
        add_fileset_file synopsys/altera_eth_gmii_mii_encoder_tx_if.v SYSTEM_VERILOG_ENCRYPT PATH "synopsys/altera_eth_gmii_mii_encoder_tx_if.v" {SYNOPSYS_SPECIFIC}
        add_fileset_file synopsys/altera_eth_gmii_encoder_dfa.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_gmii_encoder_dfa.v" {SYNOPSYS_SPECIFIC}
        add_fileset_file synopsys/altera_eth_gmii_encoder.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_gmii_encoder.v" {SYNOPSYS_SPECIFIC}
        if {$enable_timestamping} {
            add_fileset_file synopsys/altera_tse_gmii_to_avst_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii2avst_converter/synopsys/altera_tse_gmii_to_avst_if.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_tsu.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_tsu/synopsys/altera_tse_tsu.v" {SYNOPSYS_SPECIFIC}
        }
        if {$enable_ptp_1step} {
            add_fileset_file synopsys/altera_tse_ptp_inserter.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_ptp_inserter/synopsys/altera_tse_ptp_inserter.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_crc328generator.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/synopsys/altera_tse_crc328generator.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_crc32ctl8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/synopsys/altera_tse_crc32ctl8.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_crc32galois8.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/synopsys/altera_tse_crc32galois8.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_ptp_1588_crc.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_gmii_crc/synopsys/altera_tse_ptp_1588_crc.v" {SYNOPSYS_SPECIFIC}
            add_fileset_file synopsys/altera_tse_avst_to_gmii_if.v VERILOG_ENCRYPT PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/ethernet/ethernet_ucore/altera_eth_avst2gmii_converter/synopsys/altera_tse_avst_to_gmii_if.v" {SYNOPSYS_SPECIFIC}
        }
    }
    add_fileset_file altera_avalon_dc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_dc_fifo/altera_avalon_dc_fifo.v"
    add_fileset_file altera_dcfifo_synchronizer_bundle.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_dc_fifo/altera_dcfifo_synchronizer_bundle.v"

    
}

# 
# parameters
# 
add_parameter W_GMII_WIDTH INTEGER 8
set_parameter_property W_GMII_WIDTH DEFAULT_VALUE 8
set_parameter_property W_GMII_WIDTH DISPLAY_NAME W_GMII_WIDTH
set_parameter_property W_GMII_WIDTH TYPE INTEGER
set_parameter_property W_GMII_WIDTH UNITS None
set_parameter_property W_GMII_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property W_GMII_WIDTH HDL_PARAMETER true
add_parameter BITSPERSYMBOL INTEGER 8
set_parameter_property BITSPERSYMBOL DEFAULT_VALUE 8
set_parameter_property BITSPERSYMBOL DISPLAY_NAME BITSPERSYMBOL
set_parameter_property BITSPERSYMBOL TYPE INTEGER
set_parameter_property BITSPERSYMBOL ENABLED false
set_parameter_property BITSPERSYMBOL UNITS None
set_parameter_property BITSPERSYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITSPERSYMBOL HDL_PARAMETER true
add_parameter SYMBOLSPERBEAT INTEGER 8
set_parameter_property SYMBOLSPERBEAT DEFAULT_VALUE 8
set_parameter_property SYMBOLSPERBEAT DISPLAY_NAME SYMBOLSPERBEAT
set_parameter_property SYMBOLSPERBEAT TYPE INTEGER
set_parameter_property SYMBOLSPERBEAT ENABLED false
set_parameter_property SYMBOLSPERBEAT UNITS None
set_parameter_property SYMBOLSPERBEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLSPERBEAT HDL_PARAMETER true
add_parameter SYNCHRONIZER_DEPTH INTEGER 3
set_parameter_property SYNCHRONIZER_DEPTH DEFAULT_VALUE 3
set_parameter_property SYNCHRONIZER_DEPTH DISPLAY_NAME SYNCHRONIZER_DEPTH
set_parameter_property SYNCHRONIZER_DEPTH TYPE INTEGER
set_parameter_property SYNCHRONIZER_DEPTH UNITS None
set_parameter_property SYNCHRONIZER_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYNCHRONIZER_DEPTH HDL_PARAMETER true
add_parameter QUAD_SPEED_ENA INTEGER 0
set_parameter_property QUAD_SPEED_ENA DEFAULT_VALUE 0
set_parameter_property QUAD_SPEED_ENA DISPLAY_NAME QUAD_SPEED_ENA
set_parameter_property QUAD_SPEED_ENA TYPE INTEGER
set_parameter_property QUAD_SPEED_ENA UNITS None
set_parameter_property QUAD_SPEED_ENA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property QUAD_SPEED_ENA HDL_PARAMETER true

add_parameter ENABLE_TIMESTAMPING INTEGER 0
set_parameter_property ENABLE_TIMESTAMPING DISPLAY_NAME "Enable time stamping"
set_parameter_property ENABLE_TIMESTAMPING DISPLAY_HINT boolean
set_parameter_property ENABLE_TIMESTAMPING DESCRIPTION "Instantiate time stamping component"
set_parameter_property ENABLE_TIMESTAMPING IS_HDL_PARAMETER true
set_parameter_property ENABLE_TIMESTAMPING VISIBLE true

add_parameter ENABLE_PTP_1STEP INTEGER 0
set_parameter_property ENABLE_PTP_1STEP DISPLAY_NAME "Enable PTP 1-step clock support"
set_parameter_property ENABLE_PTP_1STEP DISPLAY_HINT boolean
set_parameter_property ENABLE_PTP_1STEP DESCRIPTION "Instantiate PTP 1-step clock component"
set_parameter_property ENABLE_PTP_1STEP IS_HDL_PARAMETER true
set_parameter_property ENABLE_PTP_1STEP VISIBLE true

add_parameter INTERNAL_PATH_DELAY_CYCLE_1000 INTEGER 0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 DISPLAY_NAME INTERNAL_PATH_DELAY_CYCLE_1000
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 UNITS None
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 DISPLAY_HINT ""
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 AFFECTS_GENERATION false
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 IS_HDL_PARAMETER true
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_1000 ALLOWED_RANGES 0:31

add_parameter INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 INTEGER 0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 DISPLAY_NAME INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 UNITS None
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 DISPLAY_HINT ""
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 AFFECTS_GENERATION false
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 IS_HDL_PARAMETER true
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_0 ALLOWED_RANGES 0:512

add_parameter INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 INTEGER 0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 DISPLAY_NAME INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 UNITS None
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 DISPLAY_HINT ""
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 AFFECTS_GENERATION false
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 IS_HDL_PARAMETER true
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_100_ALIGN_1 ALLOWED_RANGES 0:512

add_parameter INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 INTEGER 0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 DISPLAY_NAME INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 UNITS None
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 DISPLAY_HINT ""
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 AFFECTS_GENERATION false
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 IS_HDL_PARAMETER true
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_0 ALLOWED_RANGES 0:4096

add_parameter INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 INTEGER 0
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 DISPLAY_NAME INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 UNITS None
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 DISPLAY_HINT ""
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 AFFECTS_GENERATION false
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 IS_HDL_PARAMETER true
set_parameter_property INTERNAL_PATH_DELAY_CYCLE_10_ALIGN_1 ALLOWED_RANGES 0:4096


# 
# display items
# 


# 
# connection point mii_source_control
# 
add_interface mii_source_control conduit end
set_interface_property mii_source_control associatedClock ""
set_interface_property mii_source_control associatedReset ""
set_interface_property mii_source_control ENABLED true

add_interface_port mii_source_control mii_source_control export Output 1


# 
# connection point mii_source_error
# 
add_interface mii_source_error conduit end
set_interface_property mii_source_error associatedClock ""
set_interface_property mii_source_error associatedReset ""
set_interface_property mii_source_error ENABLED true

add_interface_port mii_source_error mii_source_error export Output 1


# 
# connection point speed_sel
# 
add_interface speed_sel conduit end
set_interface_property speed_sel associatedClock ""
set_interface_property speed_sel associatedReset ""
set_interface_property speed_sel ENABLED true


add_interface_port speed_sel speed_sel export Input 2


# 
# connection point set_1000
# 
# add_interface set_1000 conduit end
# set_interface_property set_1000 associatedClock ""
# set_interface_property set_1000 associatedReset ""
# set_interface_property set_1000 ENABLED true

# add_interface_port set_1000 set_1000 export Input 1


# 
# connection point tx_clkena
# 
add_interface tx_clkena conduit end
set_interface_property tx_clkena associatedClock ""
set_interface_property tx_clkena associatedReset ""
set_interface_property tx_clkena ENABLED true

add_interface_port tx_clkena tx_clkena export Input 1


# 
# connection point tx_clkena_half_rate
# 
add_interface tx_clkena_half_rate conduit end
set_interface_property tx_clkena_half_rate associatedClock ""
set_interface_property tx_clkena_half_rate associatedReset ""
set_interface_property tx_clkena_half_rate ENABLED true

add_interface_port tx_clkena_half_rate tx_clkena_half_rate export Input 1


# 
# connection point rx_clkena
# 
# add_interface rx_clkena conduit end
# set_interface_property rx_clkena associatedClock ""
# set_interface_property rx_clkena associatedReset ""
# set_interface_property rx_clkena ENABLED true

# add_interface_port rx_clkena rx_clkena export Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clk_mac
set_interface_property avalon_streaming_sink associatedReset reset_mac
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink txdata_sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink txdata_sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink txdata_sink_valid valid Input 1
add_interface_port avalon_streaming_sink txdata_sink_ready ready Output 1
add_interface_port avalon_streaming_sink txdata_sink_data data Input 64
add_interface_port avalon_streaming_sink txdata_sink_error error Input 3
add_interface_port avalon_streaming_sink txdata_sink_empty empty Input 3


# 
# connection point clk_gmii
# 
add_interface clk_gmii clock end
set_interface_property clk_gmii clockRate 0
set_interface_property clk_gmii ENABLED true

add_interface_port clk_gmii clk_gmii clk Input 1


# 
# connection point reset_gmii
# 
add_interface reset_gmii reset end
set_interface_property reset_gmii associatedClock clk_gmii
set_interface_property reset_gmii synchronousEdges DEASSERT
set_interface_property reset_gmii ENABLED true

add_interface_port reset_gmii reset_gmii reset Input 1


# 
# connection point clk_mac
# 
add_interface clk_mac clock end
set_interface_property clk_mac clockRate 0
set_interface_property clk_mac ENABLED true

add_interface_port clk_mac clk_mac clk Input 1


# 
# connection point reset_mac
# 
add_interface reset_mac reset end
set_interface_property reset_mac associatedClock clk_mac
set_interface_property reset_mac synchronousEdges DEASSERT
set_interface_property reset_mac ENABLED true

add_interface_port reset_mac reset_mac reset Input 1


# 
# connection point clk_gmii_rx
# 
# add_interface clk_gmii_rx clock end
# set_interface_property clk_gmii_rx clockRate 0
# set_interface_property clk_gmii_rx ENABLED true

# add_interface_port clk_gmii_rx clk_gmii_rx clk Input 1


# 
# connection point reset_gmii_rx
# 
# add_interface reset_gmii_rx reset end
# set_interface_property reset_gmii_rx associatedClock clk_gmii_rx
# set_interface_property reset_gmii_rx synchronousEdges DEASSERT
# set_interface_property reset_gmii_rx ENABLED true

# add_interface_port reset_gmii_rx reset_gmii_rx reset Input 1


# 
# connection point gmii_source_data
# 
add_interface gmii_source_data conduit end
set_interface_property gmii_source_data associatedClock ""
set_interface_property gmii_source_data associatedReset ""
set_interface_property gmii_source_data ENABLED true

add_interface_port gmii_source_data gmii_source_data export Output 8


# 
# connection point gmii_source_control
# 
add_interface gmii_source_control conduit end
set_interface_property gmii_source_control associatedClock ""
set_interface_property gmii_source_control associatedReset ""
set_interface_property gmii_source_control ENABLED true

add_interface_port gmii_source_control gmii_source_control export Output 1


# 
# connection point gmii_source_error
# 
add_interface gmii_source_error conduit end
set_interface_property gmii_source_error associatedClock ""
set_interface_property gmii_source_error associatedReset ""
set_interface_property gmii_source_error ENABLED true

add_interface_port gmii_source_error gmii_source_error export Output 1


# 
# connection point mii_source_data
# 
add_interface mii_source_data conduit end
set_interface_property mii_source_data associatedClock ""
set_interface_property mii_source_data associatedReset ""
set_interface_property mii_source_data ENABLED true

add_interface_port mii_source_data mii_source_data export Output 4


# +-----------------------------------
# | connection point path_delay
# | 
add_interface path_delay conduit end
set_interface_assignment path_delay "ui.blockdiagram.direction" Input
# set_interface_property path_delay dataBitsPerSymbol 12
# set_interface_property path_delay errorDescriptor ""
# set_interface_property path_delay maxChannel 0
# set_interface_property path_delay readyLatency 0
# set_interface_property path_delay symbolsPerBeat 1

set_interface_property path_delay ENABLED true

add_interface_port path_delay path_delay_data data Input 22
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point time_of_day_96b
# | role: time_of_day_96b
add_interface time_of_day_96b conduit end
set_interface_assignment time_of_day_96b "ui.blockdiagram.direction" Input
# set_interface_property time_of_day_96b dataBitsPerSymbol 96
# set_interface_property time_of_day_96b errorDescriptor ""
# set_interface_property time_of_day_96b maxChannel 0
# set_interface_property time_of_day_96b readyLatency 0
# set_interface_property time_of_day_96b symbolsPerBeat 1

set_interface_property time_of_day_96b ENABLED true

add_interface_port time_of_day_96b time_of_day_96b_data data Input 96
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point time_of_day_64b
# | role: time_of_day_64b
add_interface time_of_day_64b conduit end
set_interface_assignment time_of_day_64b "ui.blockdiagram.direction" Input
# set_interface_property time_of_day_64b dataBitsPerSymbol 64
# set_interface_property time_of_day_64b errorDescriptor ""
# set_interface_property time_of_day_64b maxChannel 0
# set_interface_property time_of_day_64b readyLatency 0
# set_interface_property time_of_day_64b symbolsPerBeat 1

set_interface_property time_of_day_64b ENABLED true

add_interface_port time_of_day_64b time_of_day_64b_data data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point timestamp_96b
# | 
add_interface timestamp_96b avalon_streaming start
set_interface_property timestamp_96b dataBitsPerSymbol 96
set_interface_property timestamp_96b errorDescriptor ""
set_interface_property timestamp_96b maxChannel 0
set_interface_property timestamp_96b readyLatency 0
set_interface_property timestamp_96b symbolsPerBeat 1

set_interface_property timestamp_96b associatedClock clk_gmii
set_interface_property timestamp_96b associatedReset reset_gmii
set_interface_property timestamp_96b ENABLED true

add_interface_port timestamp_96b timestamp_96b_valid valid Output 1
add_interface_port timestamp_96b timestamp_96b_data data Output 96
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point timestamp_64b
# | 
add_interface timestamp_64b avalon_streaming start
set_interface_property timestamp_64b dataBitsPerSymbol 64
set_interface_property timestamp_64b errorDescriptor ""
set_interface_property timestamp_64b maxChannel 0
set_interface_property timestamp_64b readyLatency 0
set_interface_property timestamp_64b symbolsPerBeat 1

set_interface_property timestamp_64b associatedClock clk_gmii
set_interface_property timestamp_64b associatedReset reset_gmii
set_interface_property timestamp_64b ENABLED true

add_interface_port timestamp_64b timestamp_64b_valid valid Output 1
add_interface_port timestamp_64b timestamp_64b_data data Output 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point period_ns_fns
# | 
add_interface period_ns_fns avalon_streaming end
set_interface_property period_ns_fns dataBitsPerSymbol 20
set_interface_property period_ns_fns errorDescriptor ""
set_interface_property period_ns_fns maxChannel 0
set_interface_property period_ns_fns readyLatency 0
set_interface_property period_ns_fns symbolsPerBeat 1

set_interface_property period_ns_fns associatedClock clk_gmii
set_interface_property period_ns_fns associatedReset reset_gmii
set_interface_property period_ns_fns ENABLED true

add_interface_port period_ns_fns csr_period data Input 20
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point adjust_ns_fns
# | 
add_interface adjust_ns_fns avalon_streaming end
set_interface_property adjust_ns_fns dataBitsPerSymbol 32
set_interface_property adjust_ns_fns errorDescriptor ""
set_interface_property adjust_ns_fns maxChannel 0
set_interface_property adjust_ns_fns readyLatency 0
set_interface_property adjust_ns_fns symbolsPerBeat 1

set_interface_property adjust_ns_fns associatedClock clk_gmii
set_interface_property adjust_ns_fns associatedReset reset_gmii
set_interface_property adjust_ns_fns ENABLED true

add_interface_port adjust_ns_fns csr_adjust data Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point req_ctrl_valid
# | 
add_interface req_ctrl_valid conduit end
set_interface_property req_ctrl_valid associatedClock clk_gmii
set_interface_property req_ctrl_valid associatedReset reset_gmii
set_interface_property req_ctrl_valid ENABLED true

add_interface_port req_ctrl_valid req_ctrl_signal_valid req_ctrl_valid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point time_stamp_data
# | 
add_interface time_stamp_data conduit end
set_interface_property time_stamp_data associatedClock clk_gmii
set_interface_property time_stamp_data associatedReset reset_gmii
set_interface_property time_stamp_data ENABLED true

add_interface_port time_stamp_data egress_timestamp_96_data egress_timestamp_96b  Input 96
add_interface_port time_stamp_data ingress_timestamp_96_data ingress_timestamp_96b  Input 96
add_interface_port time_stamp_data egress_timestamp_64_data egress_timestamp_64b Input 64
add_interface_port time_stamp_data ingress_timestamp_64_data ingress_timestamp_64b Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl_signal
# | 
add_interface ctrl_signal conduit end
set_interface_property ctrl_signal associatedClock clk_gmii
set_interface_property ctrl_signal associatedReset reset_gmii
set_interface_property ctrl_signal ENABLED true

add_interface_port ctrl_signal timestamp_insert timestamp_insert Input 1
add_interface_port ctrl_signal corr_insert residence_time_update Input 1
add_interface_port ctrl_signal is_ipv4_udp_ptp checksum_zero Input 1
add_interface_port ctrl_signal is_ipv6_udp_ptp checksum_correct Input 1
add_interface_port ctrl_signal is_64_bit residence_time_calc_format Input 1
add_interface_port ctrl_signal is_ieee1588v1 timestamp_format Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point octet_location
# | 
add_interface octet_location conduit end
set_interface_property octet_location associatedClock clk_gmii
set_interface_property octet_location associatedReset reset_gmii
set_interface_property octet_location ENABLED true

add_interface_port octet_location timestamp_offset offset_timestamp Input 16
add_interface_port octet_location correction_offset offset_correction_field Input 16
add_interface_port octet_location udp_checksum_offset offset_checksum_field Input 16
add_interface_port octet_location extended_2bytes_offset offset_checksum_correction Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point crc_insert_sink
# | 
add_interface crc_insert_sink avalon_streaming end
set_interface_property crc_insert_sink dataBitsPerSymbol 1
set_interface_property crc_insert_sink errorDescriptor ""
set_interface_property crc_insert_sink maxChannel 0
set_interface_property crc_insert_sink readyLatency 0
set_interface_property crc_insert_sink symbolsPerBeat 1

set_interface_property crc_insert_sink associatedClock clk_gmii
set_interface_property crc_insert_sink associatedReset reset_gmii
set_interface_property crc_insert_sink ENABLED true

add_interface_port crc_insert_sink crc_insert_sink_data data Input 1
add_interface_port crc_insert_sink crc_insert_sink_valid valid Input 1
add_interface_port crc_insert_sink crc_insert_sink_ready ready Output 1
# | 
# +-----------------------------------

proc elaborate {} {

  set symbols_per_beat [ get_parameter_value SYMBOLSPERBEAT ]
  set bits_per_symbol [ get_parameter_value BITSPERSYMBOL ]
  
  set_interface_property avalon_streaming_sink dataBitsPerSymbol $bits_per_symbol
  set_interface_property avalon_streaming_sink symbolsPerBeat $symbols_per_beat
  
  set data_width [ expr $symbols_per_beat * $bits_per_symbol ]
  set_port_property txdata_sink_data WIDTH_EXPR $data_width
  
  set empty_width [ expr int(ceil(log($symbols_per_beat) / log(2))) ]
  set_port_property txdata_sink_empty WIDTH_EXPR $empty_width
  
  set QUAD_SPEED_ENA 						    [ get_parameter_value QUAD_SPEED_ENA ]
  
  set enable_timestamping [ get_parameter_value ENABLE_TIMESTAMPING ]
  set enable_ptp_1step [ get_parameter_value ENABLE_PTP_1STEP ]
  
  if {$QUAD_SPEED_ENA == 0} {
        # 
        # connection point sel
        # 
        
        set_port_property mii_source_control TERMINATION true
        set_port_property mii_source_control TERMINATION_VALUE 0 
        
        
        set_port_property mii_source_error TERMINATION true
        set_port_property mii_source_error TERMINATION_VALUE 0 
        
       
        set_port_property mii_source_data TERMINATION true
        set_port_property mii_source_data TERMINATION_VALUE 0 
               
       
        set_port_property tx_clkena TERMINATION true
        set_port_property tx_clkena TERMINATION_VALUE 1 
        
        set_port_property tx_clkena_half_rate TERMINATION true
        set_port_property tx_clkena_half_rate TERMINATION_VALUE 1
        
        # 
    }
    
    if {$enable_timestamping == 0} {
        set_interface_property path_delay ENABLED false
        set_port_property path_delay_data TERMINATION true
        set_port_property path_delay_data TERMINATION_VALUE 0
        
        set_interface_property time_of_day_96b ENABLED false
        set_port_property time_of_day_96b_data TERMINATION true
        set_port_property time_of_day_96b_data TERMINATION_VALUE 0
        
        set_interface_property time_of_day_64b ENABLED false
        set_port_property time_of_day_64b_data TERMINATION true
        set_port_property time_of_day_64b_data TERMINATION_VALUE 0
        
        set_interface_property timestamp_96b ENABLED false
        set_port_property timestamp_96b_valid TERMINATION true
        set_port_property timestamp_96b_data TERMINATION true
        
        set_interface_property timestamp_64b ENABLED false
        set_port_property timestamp_64b_valid TERMINATION true
        set_port_property timestamp_64b_data TERMINATION true
        
        set_interface_property period_ns_fns ENABLED false
        set_port_property csr_period TERMINATION true
        set_port_property csr_period TERMINATION_VALUE 0
        
        set_interface_property adjust_ns_fns ENABLED false
        set_port_property csr_adjust TERMINATION true
        set_port_property csr_adjust TERMINATION_VALUE 0
    }
    
    if {$enable_ptp_1step == 0} {
        set_interface_property req_ctrl_valid ENABLED false
        set_port_property req_ctrl_signal_valid TERMINATION true
        set_port_property req_ctrl_signal_valid TERMINATION_VALUE 0
        
        set_interface_property time_stamp_data ENABLED false
        set_port_property egress_timestamp_96_data TERMINATION true
        set_port_property egress_timestamp_96_data TERMINATION_VALUE 0
        set_port_property ingress_timestamp_96_data TERMINATION true
        set_port_property ingress_timestamp_96_data TERMINATION_VALUE 0
        set_port_property egress_timestamp_64_data TERMINATION true
        set_port_property egress_timestamp_64_data TERMINATION_VALUE 0
        set_port_property ingress_timestamp_64_data TERMINATION true
        set_port_property ingress_timestamp_64_data TERMINATION_VALUE 0
        
        set_interface_property ctrl_signal ENABLED false
        set_port_property timestamp_insert TERMINATION true
        set_port_property timestamp_insert TERMINATION_VALUE 0
        set_port_property corr_insert TERMINATION true
        set_port_property corr_insert TERMINATION_VALUE 0
        set_port_property is_ipv4_udp_ptp TERMINATION true
        set_port_property is_ipv4_udp_ptp TERMINATION_VALUE 0
        set_port_property is_ipv6_udp_ptp TERMINATION true
        set_port_property is_ipv6_udp_ptp TERMINATION_VALUE 0
        set_port_property is_64_bit TERMINATION true
        set_port_property is_64_bit TERMINATION_VALUE 0
        set_port_property is_ieee1588v1 TERMINATION true
        set_port_property is_ieee1588v1 TERMINATION_VALUE 0
        
        set_interface_property octet_location ENABLED false
        set_port_property timestamp_offset TERMINATION true
        set_port_property timestamp_offset TERMINATION_VALUE 0
        set_port_property correction_offset TERMINATION true
        set_port_property correction_offset TERMINATION_VALUE 0
        set_port_property udp_checksum_offset TERMINATION true
        set_port_property udp_checksum_offset TERMINATION_VALUE 0
        set_port_property extended_2bytes_offset TERMINATION true
        set_port_property extended_2bytes_offset TERMINATION_VALUE 0
        
        set_interface_property crc_insert_sink ENABLED false
        set_port_property crc_insert_sink_valid TERMINATION true
        set_port_property crc_insert_sink_valid TERMINATION_VALUE 0
        set_port_property crc_insert_sink_data TERMINATION true
        set_port_property crc_insert_sink_data TERMINATION_VALUE 0
    }
  
}

