# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 10.1
# Tue Jan 25 14:51:23 MYT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_eth_preamble_custom "altera_eth_preamble_custom" v1.0
# | aishak 2011.01.25.14:51:23
# | 
# | 
# | /data/aishak/proto/altera_eth_preamble_custom.v
# | 
# |    ./altera_eth_preamble_custom.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_eth_preamble_custom
# | 
set_module_property NAME altera_eth_preamble_custom
set_module_property VERSION 13.1
set_module_property INTERNAL true
#set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME altera_eth_preamble_custom
set_module_property GROUP "Interface Protocols/Ethernet/Submodules"
set_module_property TOP_LEVEL_HDL_FILE altera_eth_preamble_custom.v
set_module_property TOP_LEVEL_HDL_MODULE altera_eth_preamble_custom
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL false
# set_module_property SIMULATION_MODEL_IN_VERILOG true
# set_module_property SIMULATION_MODEL_IN_VHDL true
# | 
# +-----------------------------------

# -----------------------------------
# IEEE encryption
# ----------------------------------- 
set HDL_LIB_DIR "../lib"

add_fileset simulation_verilog SIM_VERILOG sim_ver
add_fileset simulation_vhdl SIM_VHDL sim_vhd
set_fileset_property simulation_verilog TOP_LEVEL altera_eth_preamble_custom

proc sim_ver {name} {
    if {1} {
        add_fileset_file mentor/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "mentor/altera_eth_preamble_custom.v" {MENTOR_SPECIFIC}
    }
    if {1} {
        add_fileset_file aldec/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "aldec/altera_eth_preamble_custom.v" {ALDEC_SPECIFIC}
    }
    if {0} {
        add_fileset_file cadence/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "cadence/altera_eth_preamble_custom.v" {CADENCE_SPECIFIC}
    }
    if {0} {
        add_fileset_file synopsys/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_preamble_custom.v" {SYNOPSYS_SPECIFIC}
    }
    add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
}

proc sim_vhd {name} {
   if {1} {
      add_fileset_file mentor/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "mentor/altera_eth_preamble_custom.v" {MENTOR_SPECIFIC}
   }
   if {1} {
      add_fileset_file aldec/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "aldec/altera_eth_preamble_custom.v" {ALDEC_SPECIFIC}
   }
   if {0} {
      add_fileset_file cadence/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "cadence/altera_eth_preamble_custom.v" {CADENCE_SPECIFIC}
   }
   if {0} {
      add_fileset_file synopsys/altera_eth_preamble_custom.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_preamble_custom.v" {SYNOPSYS_SPECIFIC}
   }
   add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
}



# +-----------------------------------
# | files
# | 
add_file altera_eth_preamble_custom.v {SYNTHESIS}
add_file $::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v {SYNTHESIS}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DATA_WIDTH INTEGER 64
set_parameter_property DATA_WIDTH DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter EMPTY_WIDTH INTEGER 3
set_parameter_property EMPTY_WIDTH DEFAULT_VALUE 3
set_parameter_property EMPTY_WIDTH DISPLAY_NAME EMPTY_WIDTH
set_parameter_property EMPTY_WIDTH TYPE INTEGER
set_parameter_property EMPTY_WIDTH UNITS None
set_parameter_property EMPTY_WIDTH AFFECTS_GENERATION false
set_parameter_property EMPTY_WIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point csr
# | 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr constantBurstBehavior true
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0

set_interface_property csr ENABLED true

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_address address Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point csr_reset
# |
add_interface csr_reset reset end
set_interface_property csr_reset associatedClock clock
set_interface_property csr_reset synchronousEdges DEASSERT
set_interface_property csr_reset ENABLED true
add_interface_port csr_reset csr_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_user
# | 
add_interface avalon_streaming_sink_user avalon_streaming end
set_interface_property avalon_streaming_sink_user associatedClock clock
set_interface_property avalon_streaming_sink_user associatedReset reset
set_interface_property avalon_streaming_sink_user dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_user symbolsPerBeat 8
set_interface_property avalon_streaming_sink_user errorDescriptor ""
set_interface_property avalon_streaming_sink_user maxChannel 0
set_interface_property avalon_streaming_sink_user readyLatency 0

set_interface_property avalon_streaming_sink_user ENABLED true

add_interface_port avalon_streaming_sink_user in_ready ready Output 1
add_interface_port avalon_streaming_sink_user in_valid valid Input 1
add_interface_port avalon_streaming_sink_user in_data data Input DATA_WIDTH
add_interface_port avalon_streaming_sink_user in_error error Input 1
add_interface_port avalon_streaming_sink_user in_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink_user in_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink_user in_empty empty Input EMPTY_WIDTH
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_pkt_f
# | 
add_interface avalon_streaming_sink_pkt_f avalon_streaming end
set_interface_property avalon_streaming_sink_pkt_f associatedClock clock
set_interface_property avalon_streaming_sink_pkt_f associatedReset reset
set_interface_property avalon_streaming_sink_pkt_f dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_pkt_f symbolsPerBeat 8
set_interface_property avalon_streaming_sink_pkt_f errorDescriptor ""
set_interface_property avalon_streaming_sink_pkt_f maxChannel 0
set_interface_property avalon_streaming_sink_pkt_f readyLatency 0

set_interface_property avalon_streaming_sink_pkt_f ENABLED true

add_interface_port avalon_streaming_sink_pkt_f in_ready_2 ready Output 1
add_interface_port avalon_streaming_sink_pkt_f in_valid_2 valid Input 1
add_interface_port avalon_streaming_sink_pkt_f in_data_2 data Input DATA_WIDTH
add_interface_port avalon_streaming_sink_pkt_f in_error_2 error Input 3
add_interface_port avalon_streaming_sink_pkt_f in_startofpacket_2 startofpacket Input 1
add_interface_port avalon_streaming_sink_pkt_f in_endofpacket_2 endofpacket Input 1
add_interface_port avalon_streaming_sink_pkt_f in_empty_2 empty Input EMPTY_WIDTH
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_channel_info
# | 
add_interface avalon_streaming_sink_channel_info avalon_streaming end
set_interface_property avalon_streaming_sink_channel_info associatedClock clock
set_interface_property avalon_streaming_sink_channel_info associatedReset reset
set_interface_property avalon_streaming_sink_channel_info dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_channel_info symbolsPerBeat 8
set_interface_property avalon_streaming_sink_channel_info errorDescriptor ""
set_interface_property avalon_streaming_sink_channel_info maxChannel 1
set_interface_property avalon_streaming_sink_channel_info readyLatency 0

set_interface_property avalon_streaming_sink_channel_info ENABLED true

add_interface_port avalon_streaming_sink_channel_info in_ready_3 ready Output 1
add_interface_port avalon_streaming_sink_channel_info in_valid_3 valid Input 1
add_interface_port avalon_streaming_sink_channel_info in_channel_3 channel Input 1
add_interface_port avalon_streaming_sink_channel_info in_data_3 data Input DATA_WIDTH
add_interface_port avalon_streaming_sink_channel_info in_error_3 error Input 2
add_interface_port avalon_streaming_sink_channel_info in_startofpacket_3 startofpacket Input 1
add_interface_port avalon_streaming_sink_channel_info in_endofpacket_3 endofpacket Input 1
add_interface_port avalon_streaming_sink_channel_info in_empty_3 empty Input EMPTY_WIDTH
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source_user
# | 
add_interface avalon_streaming_source_user avalon_streaming start
set_interface_property avalon_streaming_source_user associatedClock clock
set_interface_property avalon_streaming_source_user associatedReset reset
set_interface_property avalon_streaming_source_user dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_user symbolsPerBeat 8
set_interface_property avalon_streaming_source_user errorDescriptor ""
set_interface_property avalon_streaming_source_user maxChannel 0
set_interface_property avalon_streaming_source_user readyLatency 0

set_interface_property avalon_streaming_source_user ENABLED true

add_interface_port avalon_streaming_source_user out0_ready ready Input 1
add_interface_port avalon_streaming_source_user out0_valid valid Output 1
add_interface_port avalon_streaming_source_user out0_data data Output DATA_WIDTH
add_interface_port avalon_streaming_source_user out0_error error Output 1
add_interface_port avalon_streaming_source_user out0_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source_user out0_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source_user out0_empty empty Output EMPTY_WIDTH
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point preamble_src
# | 
add_interface preamble_src avalon_streaming start
set_interface_property preamble_src associatedClock clock
set_interface_property preamble_src associatedReset reset
set_interface_property preamble_src dataBitsPerSymbol 8
set_interface_property preamble_src symbolsPerBeat 8
set_interface_property preamble_src errorDescriptor ""
set_interface_property preamble_src maxChannel 0
set_interface_property preamble_src readyLatency 0

set_interface_property preamble_src ENABLED true

add_interface_port preamble_src out1_ready ready Input 1
add_interface_port preamble_src out1_valid valid Output 1
add_interface_port preamble_src out1_data data Output DATA_WIDTH
# | 
# +-----------------------------------
