# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 11.0
# Tue Feb 08 14:09:09 MYT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_eth_preamble_inserter "Preamble Inserter" v1.0
# | null 2011.02.08.14:09:09
# | 
# | 
# | /data/aishak/p4root/acds/main/ip/ethernet/ethernet_ucore/altera_eth_preamble_inserter/altera_eth_preamble_inserter.v
# | 
# |    ./altera_eth_preamble_inserter.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_eth_preamble_inserter
# | 
set_module_property NAME altera_eth_preamble_inserter
set_module_property VERSION 13.1
set_module_property AUTHOR "Altera Corporation"
set_module_property INTERNAL true
#set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Ethernet/Submodules"
set_module_property DISPLAY_NAME "Preamble Inserter"
set_module_property TOP_LEVEL_HDL_FILE altera_eth_preamble_inserter.v
set_module_property TOP_LEVEL_HDL_MODULE altera_eth_preamble_inserter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL false
# set_module_property SIMULATION_MODEL_IN_VERILOG true
# set_module_property SIMULATION_MODEL_IN_VHDL true
# | 
# +-----------------------------------

# -----------------------------------
# IEEE encryption
# ----------------------------------- 
set HDL_LIB_DIR "../lib"

add_fileset simulation_verilog SIM_VERILOG sim_ver
add_fileset simulation_vhdl SIM_VHDL sim_vhd
set_fileset_property simulation_verilog TOP_LEVEL altera_eth_preamble_inserter

proc sim_ver {name} {
    if {1} {
        add_fileset_file mentor/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "mentor/altera_eth_preamble_inserter.v" {MENTOR_SPECIFIC}
    }
    if {1} {
        add_fileset_file aldec/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "aldec/altera_eth_preamble_inserter.v" {ALDEC_SPECIFIC}
    }
    if {0} {
        add_fileset_file cadence/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "cadence/altera_eth_preamble_inserter.v" {CADENCE_SPECIFIC}
    }
    if {0} {
        add_fileset_file synopsys/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_preamble_inserter.v" {SYNOPSYS_SPECIFIC}
    }
    add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
}

proc sim_vhd {name} {
   if {1} {
      add_fileset_file mentor/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "mentor/altera_eth_preamble_inserter.v" {MENTOR_SPECIFIC}
   }
   if {1} {
      add_fileset_file aldec/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "aldec/altera_eth_preamble_inserter.v" {ALDEC_SPECIFIC}
   }
   if {0} {
      add_fileset_file cadence/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "cadence/altera_eth_preamble_inserter.v" {CADENCE_SPECIFIC}
   }
   if {0} {
      add_fileset_file synopsys/altera_eth_preamble_inserter.v VERILOG_ENCRYPT PATH "synopsys/altera_eth_preamble_inserter.v" {SYNOPSYS_SPECIFIC}
   }
   add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH "$::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"
}


# +-----------------------------------
# | files
# | 
add_file altera_eth_preamble_inserter.v {SYNTHESIS}
add_file $::env(QUARTUS_ROOTDIR)/../ip/altera/sopc_builder_ip/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v {SYNTHESIS}

# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter BITSPERSYMBOL INTEGER 8
set_parameter_property BITSPERSYMBOL DEFAULT_VALUE 8
set_parameter_property BITSPERSYMBOL DISPLAY_NAME BITSPERSYMBOL
set_parameter_property BITSPERSYMBOL TYPE INTEGER
set_parameter_property BITSPERSYMBOL UNITS None
set_parameter_property BITSPERSYMBOL AFFECTS_GENERATION false
set_parameter_property BITSPERSYMBOL HDL_PARAMETER true
add_parameter SYMBOLSPERBEAT INTEGER 8
set_parameter_property SYMBOLSPERBEAT DEFAULT_VALUE 8
set_parameter_property SYMBOLSPERBEAT DISPLAY_NAME SYMBOLSPERBEAT
set_parameter_property SYMBOLSPERBEAT TYPE INTEGER
set_parameter_property SYMBOLSPERBEAT UNITS None
set_parameter_property SYMBOLSPERBEAT AFFECTS_GENERATION false
set_parameter_property SYMBOLSPERBEAT HDL_PARAMETER true
add_parameter ERRORWIDTH INTEGER 5
set_parameter_property ERRORWIDTH DEFAULT_VALUE 5
set_parameter_property ERRORWIDTH DISPLAY_NAME ERRORWIDTH
set_parameter_property ERRORWIDTH TYPE INTEGER
set_parameter_property ERRORWIDTH UNITS None
set_parameter_property ERRORWIDTH AFFECTS_GENERATION false
set_parameter_property ERRORWIDTH HDL_PARAMETER true
add_parameter STATUSWIDTH INTEGER 23
set_parameter_property STATUSWIDTH DEFAULT_VALUE 23
set_parameter_property STATUSWIDTH DISPLAY_NAME STATUSWIDTH
set_parameter_property STATUSWIDTH TYPE INTEGER
set_parameter_property STATUSWIDTH UNITS None
set_parameter_property STATUSWIDTH AFFECTS_GENERATION false
set_parameter_property STATUSWIDTH HDL_PARAMETER true
add_parameter EMPTYWIDTH INTEGER 3
set_parameter_property EMPTYWIDTH DEFAULT_VALUE 3
set_parameter_property EMPTYWIDTH DISPLAY_NAME EMPTYWIDTH
set_parameter_property EMPTYWIDTH TYPE INTEGER
set_parameter_property EMPTYWIDTH UNITS None
set_parameter_property EMPTYWIDTH AFFECTS_GENERATION false
set_parameter_property EMPTYWIDTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point csr
# | 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr constantBurstBehavior true
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitStates 0
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0

set_interface_property csr ENABLED true

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_address address Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point csr_reset
# |
add_interface csr_reset reset end
set_interface_property csr_reset associatedClock clock
set_interface_property csr_reset synchronousEdges DEASSERT
set_interface_property csr_reset ENABLED true
add_interface_port csr_reset csr_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_data_line
# | 
add_interface avalon_streaming_sink_data_line avalon_streaming end
set_interface_property avalon_streaming_sink_data_line associatedClock clock
set_interface_property avalon_streaming_sink_data_line associatedReset reset
set_interface_property avalon_streaming_sink_data_line dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_data_line errorDescriptor ""
set_interface_property avalon_streaming_sink_data_line highOrderSymbolAtMSB false
set_interface_property avalon_streaming_sink_data_line maxChannel 0
set_interface_property avalon_streaming_sink_data_line readyLatency 0

set_interface_property avalon_streaming_sink_data_line ENABLED true

add_interface_port avalon_streaming_sink_data_line line_data_sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink_data_line line_data_sink_eop endofpacket Input 1
add_interface_port avalon_streaming_sink_data_line line_data_sink_valid valid Input 1
add_interface_port avalon_streaming_sink_data_line line_data_sink_data data Input 64
add_interface_port avalon_streaming_sink_data_line line_data_sink_empty empty Input EMPTYWIDTH
add_interface_port avalon_streaming_sink_data_line line_data_sink_error error Input 5
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_packet_status
# | 
add_interface avalon_streaming_sink_packet_status avalon_streaming end
set_interface_property avalon_streaming_sink_packet_status associatedClock clock
set_interface_property avalon_streaming_sink_packet_status associatedReset reset
set_interface_property avalon_streaming_sink_packet_status dataBitsPerSymbol 40
set_interface_property avalon_streaming_sink_packet_status errorDescriptor ""
set_interface_property avalon_streaming_sink_packet_status highOrderSymbolAtMSB false
set_interface_property avalon_streaming_sink_packet_status maxChannel 0
set_interface_property avalon_streaming_sink_packet_status readyLatency 0

set_interface_property avalon_streaming_sink_packet_status ENABLED true

add_interface_port avalon_streaming_sink_packet_status data_sink_valid valid Input 1
add_interface_port avalon_streaming_sink_packet_status data_sink_data data Input 40
add_interface_port avalon_streaming_sink_packet_status data_sink_error error Input 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point preamble_sink
# | 
add_interface preamble_sink avalon_streaming end
set_interface_property preamble_sink associatedClock clock
set_interface_property preamble_sink associatedReset reset
set_interface_property preamble_sink dataBitsPerSymbol 8
set_interface_property preamble_sink errorDescriptor ""
set_interface_property preamble_sink highOrderSymbolAtMSB false
set_interface_property preamble_sink maxChannel 0
set_interface_property preamble_sink readyLatency 0

set_interface_property preamble_sink ENABLED true

add_interface_port preamble_sink preamble_valid valid Input 1
add_interface_port preamble_sink preamble_bytes data Input 64
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source_data_line
# | 
add_interface avalon_streaming_source_data_line avalon_streaming start
set_interface_property avalon_streaming_source_data_line associatedClock clock
set_interface_property avalon_streaming_source_data_line associatedReset reset
set_interface_property avalon_streaming_source_data_line dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_data_line errorDescriptor ""
set_interface_property avalon_streaming_source_data_line highOrderSymbolAtMSB false
set_interface_property avalon_streaming_source_data_line maxChannel 0
set_interface_property avalon_streaming_source_data_line readyLatency 0

set_interface_property avalon_streaming_source_data_line ENABLED true

add_interface_port avalon_streaming_source_data_line data_source_sop startofpacket Output 1
add_interface_port avalon_streaming_source_data_line data_source_eop endofpacket Output 1
add_interface_port avalon_streaming_source_data_line data_source_valid valid Output 1
add_interface_port avalon_streaming_source_data_line data_source_data data Output 64
add_interface_port avalon_streaming_source_data_line data_source_empty empty Output EMPTYWIDTH
add_interface_port avalon_streaming_source_data_line data_source_error error Output 5
# | 
# +-----------------------------------
