# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 13.0
# Fri Oct 05 13:50:31 PDT 2012
# DO NOT MODIFY


# 
# arm_a9 "Arm A9" v1.0
# null 2012.10.05.13:50:31
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1
source hps_utils.tcl



# 
# module arm_a9
# 
set_module_property NAME arm_a9
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME "ARM A9"
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 

# 
# parameters
# 
set_module_assignment embeddedsw.dts.vendor "arm"
set_module_assignment embeddedsw.dts.name "cortex-a9"
set_module_assignment embeddedsw.dts.group "cpu"
set_module_assignment embeddedsw.dts.compatible {arm,cortex-a9}

# 
# display items
# 


# 
# connection point altera_axi_master
# 

add_parameter address_map string
set_parameter_property address_map system_info_type address_map
set_parameter_property address_map system_info_arg altera_axi_master



hps_utils_add_axi_master altera_axi_master new_signal clock_sink reset_sink 1 32 32 4

# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink new_signal_22 reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink new_signal_23 clk Input 1

