# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 11.0
# Mon Jul 25 14:20:19 BST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_trace_av_st_example_distiller "altera_trace_av_st_example_distiller" v1.0
# | null 2011.07.25.14:20:19
# | 
# | 
# | S:/data/pclarke/p4_dev/acds/main/ssg/ip/altera_trace/altera_trace_av_st_example_distiller/altera_trace_av_st_example_distiller.v
# | 
# |    ./altera_trace_av_st_example_distiller.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_trace_av_st_example_distiller
# | 
set_module_property NAME                          altera_trace_trigger_monitor
set_module_property VERSION                       13.1
set_module_property AUTHOR                        "Altera Corporation"
set_module_property INTERNAL                      true
set_module_property OPAQUE_ADDRESS_MAP            true
set_module_property DISPLAY_NAME                  "Trigger monitor"
set_module_property GROUP                         "Verification/Debug & Performance/Trace"
set_module_property TOP_LEVEL_HDL_FILE            altera_trace_trigger_monitor.v
set_module_property TOP_LEVEL_HDL_MODULE          altera_trace_trigger_monitor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE  true
set_module_property EDITABLE                      true
set_module_property ANALYZE_HDL                   false
set_module_property STATIC_TOP_LEVEL_MODULE_NAME  "altera_trace_trigger_monitor"
set_module_property FIX_110_VIP_PATH              false
set_module_property ELABORATION_CALLBACK          elaborate
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file altera_trace_trigger_monitor.v                        {SYNTHESIS SIMULATION}
add_file altera_trace_trigger_monitor_core.v                   {SYNTHESIS SIMULATION}
add_file altera_trace_trigger_monitor_buffered_width_adapter.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 


proc proc_add_parameter {NAME TYPE DEFAULT IS_HDL VISIBLE AFFECTS_GENERATION GROUP DISP_NAME DESCRIPTION  args} {
    add_parameter           $NAME $TYPE $DEFAULT $DESCRIPTION
    if {$args != ""} then {
        set_parameter_property  $NAME "ALLOWED_RANGES" $args
    }
    set_parameter_property  $NAME "VISIBLE"            $VISIBLE
    set_parameter_property  $NAME "HDL_PARAMETER"      $IS_HDL
    set_parameter_property  $NAME "GROUP"              $GROUP
    set_parameter_property  $NAME "DISPLAY_NAME"       $DISP_NAME
    set_parameter_property  $NAME "AFFECTS_GENERATION" $AFFECTS_GENERATION
}

#                    name                      type   def_value            is_hdl   VISIBLE  Affects     group     display name             Tooltip hint                                                         args_range
#                                                                                         generation
#proc_add_parameter ARGWIDTH                   INTEGER    32               false   true      false        ""       "Argument Width"      "Enter an appropriate altera device family"
proc_add_parameter  DEVICE_FAMILY              STRING    "Cyclone IV GX"   true    false     false         ""       "Device family"        "monitored data width"                                                                                                                                                                                                                                                                           
proc_add_parameter  TRACE_OUT_SYMBOL_WIDTH     INTEGER    4                true    true      true         ""       "Output symbol width"  "output num symbols"                
proc_add_parameter  FULL_TS_LENGTH             INTEGER    48               true    true      true         ""       "Timestamp width"      "full timestamp width"              
proc_add_parameter  WAKE_UP_RUNNING            INTEGER    0                true    true      true         ""       "Wake up running"      "if set to 1 then triggering can happend from startup"                  0:1
proc_add_parameter  BUFFER_DEPTH_WIDTH         INTEGER    3                true    true      true         ""       "Buffer size"          "this is the numebr of bits used for the addressing in the buffer"      1:8


set_parameter_property DEVICE_FAMILY SYSTEM_INFO DEVICE_FAMILY
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point clk
# | 
add_interface          clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface          reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
add_interface_port     reset arst_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point csr_s
# | 
add_interface csr_s avalon end
set_interface_property csr_s addressUnits                   WORDS
set_interface_property csr_s associatedClock                clk
set_interface_property csr_s associatedReset                reset
set_interface_property csr_s bitsPerSymbol                  8
set_interface_property csr_s burstOnBurstBoundariesOnly     false
set_interface_property csr_s burstcountUnits                WORDS
set_interface_property csr_s explicitAddressSpan            0
set_interface_property csr_s holdTime                       0
set_interface_property csr_s linewrapBursts                 false
set_interface_property csr_s maximumPendingReadTransactions 0
set_interface_property csr_s readLatency                    2
set_interface_property csr_s readWaitStates                 0
set_interface_property csr_s readWaitTime                   0
set_interface_property csr_s setupTime                      0
set_interface_property csr_s timingUnits                    Cycles
set_interface_property csr_s writeWaitTime                  0

set_interface_property csr_s ENABLED                        true

add_interface_port csr_s csr_s_read       read      Input  1
add_interface_port csr_s csr_s_address    address   Input  4
add_interface_port csr_s csr_s_readdata   readdata  Output 32
add_interface_port csr_s csr_s_write      write     Input  1
add_interface_port csr_s csr_s_write_data writedata Input  32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point trigger_input
# | 
add_interface          trigger_input avalon_streaming           end
set_interface_property trigger_input ENABLED                    true
set_interface_property trigger_input associatedClock            clk
set_interface_property trigger_input associatedReset            reset
set_interface_property trigger_input readyLatency               0

add_interface_port     trigger_input iut_st_valid  valid        Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface          capture avalon_streaming           start
set_interface_property capture associatedClock            clk
set_interface_property capture associatedReset            reset
set_interface_property capture dataBitsPerSymbol          8
set_interface_property capture errorDescriptor            ""
set_interface_property capture firstSymbolInHighOrderBits true
set_interface_property capture maxChannel                 0
set_interface_property capture readyLatency               0

set_interface_property capture ENABLED true
set_interface_assignment capture debug.providesServices traceMonitor
set_interface_assignment capture debug.interfaceGroup {associatedControl csr_s}
set_interface_assignment capture debug.monitoredInterfaces trigger_input

add_interface_port capture av_st_tr_ready ready         Input  1
add_interface_port capture av_st_tr_valid valid         Output 1
add_interface_port capture av_st_tr_sop   startofpacket Output 1
add_interface_port capture av_st_tr_eop   endofpacket   Output 1

# | 
# +-----------------------------------

proc log2ceil {num} {
    #make log(0), log(1) = 1
    set val 1
    set i 1
    while {$i < $num} {
        set val [expr $val + 1]
        set i [expr 1 << $val]
    }
    return $val;
}




#proc validate {} {
#  TODO: validate that outputs with >= TS_WIDTH + 2	
#}

proc elaborate {} {
   add_interface_port capture av_st_tr_data  data  Output [expr [get_parameter_value TRACE_OUT_SYMBOL_WIDTH]  * 8]
   add_interface_port capture av_st_tr_empty empty Output [log2ceil [get_parameter_value TRACE_OUT_SYMBOL_WIDTH]]
}        

