# (C) 2001-2013 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 11.0
# Wed Jun 01 12:32:28 BST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | altera_trace_timestamp_distiller "timestampdistiller" v1.0
# | null 2011.06.01.12:32:28
# | 
# | 
# | S:/data/pclarke/p4_dev/acds/main/ssg/ip/altera_trace/altera_trace_ts_module/altera_trace_timestamp_distiller.v
# | 
# |    ./altera_trace_timestamp_distiller.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module altera_trace_timestamp_distiller
# | 
set_module_property NAME                         altera_trace_timestamp_monitor
set_module_property VERSION                      13.1
set_module_property AUTHOR                       "Altera Corporation"
set_module_property INTERNAL                     true
set_module_property OPAQUE_ADDRESS_MAP           true
set_module_property GROUP                        "Verification/Debug & Performance/Trace"
set_module_property DISPLAY_NAME                 "Timestamp monitor"
set_module_property TOP_LEVEL_HDL_FILE           altera_trace_timestamp_monitor.v
set_module_property TOP_LEVEL_HDL_MODULE         altera_trace_timestamp_monitor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE                     true
set_module_property ANALYZE_HDL                  false
set_module_property STATIC_TOP_LEVEL_MODULE_NAME "altera_trace_timestamp_monitor"
set_module_property ELABORATION_CALLBACK         elaborate


# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file altera_trace_timestamp_monitor.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter TRACE_DATA_WIDTH INTEGER 32
set_parameter_property TRACE_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property TRACE_DATA_WIDTH DISPLAY_NAME TRACE_DATA_WIDTH
set_parameter_property TRACE_DATA_WIDTH TYPE INTEGER
set_parameter_property TRACE_DATA_WIDTH UNITS None
set_parameter_property TRACE_DATA_WIDTH AFFECTS_GENERATION true
set_parameter_property TRACE_DATA_WIDTH HDL_PARAMETER true

add_parameter TRACE_SYMBOL_WIDTH INTEGER 8
set_parameter_property TRACE_SYMBOL_WIDTH DEFAULT_VALUE 8
set_parameter_property TRACE_SYMBOL_WIDTH DISPLAY_NAME TRACE_SYMBOL_WIDTH
set_parameter_property TRACE_SYMBOL_WIDTH TYPE INTEGER
set_parameter_property TRACE_SYMBOL_WIDTH UNITS None
set_parameter_property TRACE_SYMBOL_WIDTH VISIBLE FALSE
set_parameter_property TRACE_SYMBOL_WIDTH AFFECTS_GENERATION true
set_parameter_property TRACE_SYMBOL_WIDTH HDL_PARAMETER true

add_parameter FULL_TS_LENGTH INTEGER 40
set_parameter_property FULL_TS_LENGTH DEFAULT_VALUE 40
set_parameter_property FULL_TS_LENGTH DISPLAY_NAME FULL_TS_LENGTH
set_parameter_property FULL_TS_LENGTH TYPE INTEGER
set_parameter_property FULL_TS_LENGTH UNITS None
set_parameter_property FULL_TS_LENGTH AFFECTS_GENERATION true
set_parameter_property FULL_TS_LENGTH HDL_PARAMETER true

add_parameter SHORT_TS_BITS INTEGER 16
set_parameter_property SHORT_TS_BITS DEFAULT_VALUE 16
set_parameter_property SHORT_TS_BITS DISPLAY_NAME SHORT_TS_BITS
set_parameter_property SHORT_TS_BITS TYPE INTEGER
set_parameter_property SHORT_TS_BITS UNITS None
set_parameter_property SHORT_TS_BITS AFFECTS_GENERATION false
set_parameter_property SHORT_TS_BITS HDL_PARAMETER true

add_parameter          SYNC_DEPTH INTEGER 3
set_parameter_property SYNC_DEPTH DEFAULT_VALUE 3
set_parameter_property SYNC_DEPTH DISPLAY_NAME SYNC_DEPTH
set_parameter_property SYNC_DEPTH TYPE INTEGER
set_parameter_property SYNC_DEPTH UNITS None
set_parameter_property SYNC_DEPTH AFFECTS_GENERATION false
set_parameter_property SYNC_DEPTH HDL_PARAMETER true

add_parameter          USE_TS_OUT BOOLEAN FALSE
set_parameter_property USE_TS_OUT DEFAULT_VALUE FALSE
set_parameter_property USE_TS_OUT DISPLAY_NAME USE_TS_OUT
set_parameter_property USE_TS_OUT TYPE BOOLEAN
set_parameter_property USE_TS_OUT UNITS none
set_parameter_property USE_TS_OUT AFFECTS_GENERATION true
set_parameter_property USE_TS_OUT HDL_PARAMETER false


# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface          clock clock     end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED   true
add_interface_port     clock clk       clk  Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface          reset_sink reset            end
set_interface_property reset_sink associatedClock  clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED          true
add_interface_port     reset_sink arst_n           reset_n   Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point full_ts_out
# | 
add_interface          full_ts_out avalon_streaming start
set_interface_property full_ts_out associatedClock clock
set_interface_property full_ts_out associatedReset reset_sink
set_interface_property full_ts_out dataBitsPerSymbol 1
set_interface_property full_ts_out errorDescriptor ""
set_interface_property full_ts_out firstSymbolInHighOrderBits true
set_interface_property full_ts_out maxChannel 0
set_interface_property full_ts_out readyLatency 0
add_interface_port     full_ts_out full_ts data Output FULL_TS_LENGTH
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point av_st_trace_event_out
# | 


# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ts_sync_req
# | 
add_interface ts_sync_req clock end
#set_interface_property ts_sync_req clockRate 0

set_interface_property ts_sync_req ENABLED true

add_interface_port ts_sync_req async_ts_sync_clk clk Input 1
# | 
# +-----------------------------------


proc log2ceil {num} {
    #make log(0), log(1) = 1
    set val 1
    set i 1
    while {$i < $num} {
        set val [expr $val + 1]
        set i [expr 1 << $val]
    }
    return $val;
}

proc elaborate {} {
	set data_symbols [log2ceil [expr [get_parameter_value TRACE_DATA_WIDTH] / 8]]
    add_interface          capture avalon_streaming start
    set_interface_property capture associatedClock clock
    set_interface_property capture associatedReset reset_sink
    set_interface_property capture dataBitsPerSymbol [get_parameter_value TRACE_SYMBOL_WIDTH]
    set_interface_property capture errorDescriptor ""
    set_interface_property capture firstSymbolInHighOrderBits true
    set_interface_property capture maxChannel 0
    set_interface_property capture readyLatency 0
    set_interface_property capture ENABLED true
    add_interface_port     capture av_st_tr_ready ready         Input  1
    add_interface_port     capture av_st_tr_valid valid         Output 1
    add_interface_port     capture av_st_tr_sop   startofpacket Output 1
    add_interface_port     capture av_st_tr_eop   endofpacket   Output 1
    add_interface_port     capture av_st_tr_data  data          Output [get_parameter_value TRACE_DATA_WIDTH]	
	add_interface_port     capture av_st_tr_empty empty Output  $data_symbols	

	
	if {[get_parameter_value USE_TS_OUT]} {	
		set_interface_property full_ts_out ENABLED true
	} else {
		set_interface_property full_ts_out ENABLED false
		set_port_property     full_ts TERMINATION       TRUE
		#set_port_property     full_ts TERMINATION_VALUE 0
	}
}
