// (C) 2001-2013 Altera Corporation. All rights reserved.
// This simulation model contains highly confidential and
// proprietary information of Altera and is being provided
// in accordance with and subject to the protections of the
// applicable Altera Program License Subscription Agreement
// which governs its use and disclosure. Your use of Altera
// Corporation's design tools, logic functions and other
// software and tools, and its AMPP partner logic functions,
// and any output files any of the foregoing (including device
// programming or simulation files), and any associated
// documentation or information are expressly subject to the
// terms and conditions of the Altera Program License Subscription
// Agreement, Altera MegaCore Function License Agreement, or other
// applicable license agreement, including, without limitation,
// that your use is for the sole purpose of simulating designs
// for use exclusively in logic devices manufactured by Altera and sold
// by Altera or its authorized distributors. Please refer to the
// applicable agreement for further details. Altera products and
// services are protected under numerous U.S. and foreign patents,
// maskwork rights, copyrights and other intellectual property laws.
// Altera assumes no responsibility or liability arising out of the
// application or use of this simulation model.
// ACDS 13.1
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent= "Aldec protectip, Riviera-PRO 2011.10.82"
`pragma protect key_keyowner= "Aldec", key_keyname= "ALDEC08_001", key_method= "rsa"
`pragma protect key_block encoding= (enctype="base64")
a3WCNG7FwrlWmAkXSGIEODtH/wrkhIPBE7zjXy/axDUntXWR6YwCWYFuEbT9nG7gCz0o8k5foyrr
LqvDH/mbFXg1HE3ge5uK0catK6xzDOdogwYHOhMNy9vIwA7hclKH0cPiN3ykZY2KD7Z7FaUM6pC8
SrPOJtDAueQL+5xADAaDR6sWRSsjYlILX5kLjRyj9NM5Dj2VJbFoiOEYX1NToAZX2Ydpl285nfhc
E1LI2YlgdrSR2K7PFX1bcl0GVawmHSDxzlSZOFkbd8S9e6sTBQTTMYYuENSzgYZfp6qwJUEaa68z
H8LIQkmjqHOrC4oqIBZaZvxJJJ8gi833rzBRZw==
`pragma protect data_keyowner= "altera", data_keyname= "altera"
`pragma protect data_method= "aes128-cbc"
`pragma protect data_block encoding= (enctype="base64")
AgzuWtT7VTxF8S07RdX0VAS9hk01V2iECKDiz97WbB94q2XGrD77IFe0ogXpLnATc4+i4OXXDAgQ
0xBUkgINVfnL0Y7uIWEaw47ZoU3xSz4dKIqJqZjD4yBoplUiGqn6vS3484whnFwlSw66CsoDIVUv
w0qwo5eGNEHilwsObwkfT8jz4KszLkHgH/NKXWAuLyTzRW7ulhwJ4AjHyxihPakjogk7FcENeZBn
n1HCfmrVGjlP4G0+0RiBBnwZ0DgultwAUMpTmdHmqtwL0qK9jV7IA6vZVSwru5MdnjDlMuNIaM2H
Gtog1XYjjpIuJmVizh0jLnhUPCQ0sqvZoomE2VLGij9NeW8dbUFwXOgBkoPHSrWrSr0I66TUo522
NW2Vw+FdI6uGg1ox/C0TneyNOZUg0LAI2LqfD8LsZM9YCaKM2gKdADV3u1KoSjFgRMd35OEL8D+I
GJJ50x3f8HEPSZUoaLuBTPGXQ4aufxjoxcASlcjZokppsww77mgotOQnHpRh1ajkLRNAzxbnoBc4
OD4gcCtzHGcqIemHnFalXnQ/PYhQ1DrGbZ750W/y8Lfia51jyTLlbbqRVw9ys8VvfsFTDzeXkUUU
rJGXAhsrE0EV2Oy6RmdkwgVB9wJ7s3Io2O+DX3kfZjShp6uK7UskWojIbP99asg5CZy0r/310PQ+
d8R5Z4rxfJ49+PGrK7LcezjvSCkueqCQuJsFr8g8prlZaBmq4vmO6N3j972mY4Qw0MkHQpvQ2Bpk
pNmTvPPSRJUubiXrhNUcjpBmWKbPTyUBOAynnWbKeCkuZvOgdpNyrJKthPpz5+DMYuP6FBKeoanu
lFcqjm+0Il6J1SpEvHNePNR51WRlBPs/VB/Cn1YSUJg/imot04VV17nXLrGr372QvqWnOzLpd3Ou
4EqnknNdqMzLGiaTlHxys+OEpTtD6C4ZAmXLnmNO6oOPnEzIAYSnoZ0071HDpSwfuTI5juDCjHx7
84vHQBnvcUxLS+/qfHHh9zxiRpz8cv8wM4WMtnazWVc+NgIsTukTJLh0YjsSLWStwuCLM7WiT+Kn
OMPIen/gxl2LG/Q6DRdn6QlIFJv9sEhSiJxzQq0jLSd2NvlC66sGCOHnQPxgzv5ydz93zwXOcBQG
IQ5xsunwX9xUVr8miLrtQQO8uSWt+BToBREslAaMhhHxLNda1GbOC9ZYT6ROgy1f107hp2Fwguxi
cIbCqw3268E8B1VsbpCCtyi1yCLCZILaI38qpWVLlWyp8u4T3cMkEBgEAaaycgZtDB+QFhisplmh
uhMTz5njpDn53RBaT3M82nTJgYwSdVZr5BArha4a+JVVn9+bJvM0heVAm/yuGMkXUHyssxZFrLHJ
4OA+hawFJNE1pxAmPdlEDF3wDnzVAL9M9J5Q9WwwVquq5FvftyetK0aBlbHZigk7Xy+GXtYdsHqD
KvBnDsDuUIjLj/ve/VrUuaGZSL0vVWA4t3+cwqlIy5kJoIp2m56GS+7KxiI7QQI8fHzEIKMksfG6
XZIOthmWGp4D4YnRAsGBHF5wbMQWUnYFCgC1iOcAKzcL9wz6aQIEDIrRUpcP2ospuVBOHZHqrNzD
O1aFilBWYuGx5KJ+iZj+nbEcXj50oQJJfewnfPBsr07OdvK+G4e6yGTyNfvYHzz47HgZZVrbBvWA
BPhKlO1L3T+d9+qZI7jTWH2glGBED/FA8RcwiV9LDHOqVziYFWY7BfDtu2Y6MIJHtlCW2o9uKoV3
1P4ZVecCYy9YnUhyqzpO9WPvSdFPYElU+yCm0UzB/00gmYaO4k5pRbjQ2TcvtFV2fYrfXkZiSe7R
IJVYpMGrZfxAdRQ1BbZNbo7JQdpTEx7wCtAffxlbA1S4TBbqJzCmqJpSMSD8vuzPn0Ymu/W/hsdK
LwR/oOKpNXmrTSRfuJnSMBPhK6KF+gJbyYTjkLu2F6jyF3OcPS29rmEkqqSROSMW/HDZOvt/Jzwv
1hBZeqmyNraW4Y4pyPMThYc2UOPiqsaE66d2NMddIs9jTiXx1CSOHAvgKKnyJOvaZnooMcUnvh/y
xJ5TyYOaunHCSZslddj1pu44efzO9EjdXFNLHz2Dwbro7Qsth2K4fIYkCHuajewURETtFh2qvfCu
SCLoDuxlPGhEYRMFyMy0kUFIsZQ+5FNo8ZELI8NALTn4dF2z6qd2ls6pcx9SJI1hEKgkvJfotL9e
Sm7sfFnp1e735chXTzGoDoDD6VFMQPYjmLDcZ4wwJAgsWvNFNIYzHIvHeZ7ikALf72G4EtR9Uz3G
kVQic5MptXmFSHMnXmabeVO6Kax66cGU1x6zthiPfb2YbYLURqdDxJHmPRwlw5S3MVEhs/L0TeVT
Q7ySki354sADwDBMvY5XKXaSxLZewKDPRvITx+AsyVVTIpS/0wSNoKgljP5rUFg5eSI3wx3NjPtg
SOQe6NdRfffNIGPX4+NW6xBN9aAF+Hgh9O3EnFUrBo5WnQxDBEQGwNCFR8pA3Zi4NJA8vhd0cLBy
18tdMh8Jk2PQaE22dc3qvWlxR7L3qioi0qLmFwrpOWNv9rf0CKAe48CJa7gxWRssD9U4OnQWEVZe
e90eoRKXs5jnu0Dq8xOQN2tSmA4Dx0Rm3f+8dxG7QC4iYQs9Y4GGFbJXiglRmbT0LRqx4Mpugu+K
VPecqpL+uUgYjAuIqNHcJITW1dKddGsIdJqOvst2jty92gH+EiYF0SV3HLH8+2WTn8IRu/mxPVTQ
ohLxWliOMLTQGuclthKtjePD+SQr8kqtWrCh6ZlsVlWN0WjWHN6j6vW+c4qezN91EH6T5/RDiV8i
LMKikT6AU9g/4y1MJTGJu7fxuo9xsBv3KL5CLmCnRAzgwtvHJbxIJsqSh3kS1KutbMQkUrhqOvsM
/0zkWKPrTOBHvp8Q5sDR6V0iD1M/Y1ojgElDj/IrxmfQVXQMXQQ6KvAI
`pragma protect end_protected
